import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $IEntityWithComplexSpawn } from "@package/net/neoforged/neoforge/entity";
import { $TrailAction } from "@package/dev/xkmc/danmakuapi/content/spell/spellcard";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $LivingEntity, $PortalProcessor, $Entity, $TraceableEntity } from "@package/net/minecraft/world/entity";
import { $IDanmakuEntity } from "@package/dev/xkmc/danmakuapi/api";
import { $ItemSupplier } from "@package/net/minecraft/world/entity/projectile";
import { $DanmakuMover } from "@package/dev/xkmc/danmakuapi/content/spell/mover";
import { $RandomSource } from "@package/net/minecraft/util";
import { $HolderLookup$Provider, $BlockPos } from "@package/net/minecraft/core";
import { $SimplifiedProjectile, $BaseLaser, $BaseProjectile } from "@package/dev/xkmc/fastprojectileapi/entity";
import { $BaguAnimationController } from "@package/bagu_chan/bagus_lib/animation";
import { $EntityHitResult, $Vec3_ } from "@package/net/minecraft/world/phys";
import { $DamageSource } from "@package/net/minecraft/world/damagesource";

declare module "@package/dev/xkmc/danmakuapi/content/entity" {
    export class $DanmakuLaserEntity extends $BaseLaser implements $IEntityWithComplexSpawn, $IDanmakuEntity {
        setup(arg0: number, arg1: number, arg2: number, arg3: boolean, arg4: number, arg5: number): void;
        setup(arg0: number, arg1: number, arg2: number, arg3: boolean, arg4: $Vec3_): void;
        effectiveLength(arg0: number): number;
        percentOpen(arg0: number): number;
        percentLoad(arg0: number): number;
        asTraceable(): $TraceableEntity;
        damage(arg0: $Entity): number;
        addAdditionalSaveData(arg0: $CompoundTag_): void;
        readAdditionalSaveData(arg0: $CompoundTag_): void;
        setupTime(arg0: number, arg1: number, arg2: number, arg3: number): void;
        source(): $DamageSource;
        self(): $SimplifiedProjectile;
        shouldHurt(arg0: $Entity, arg1: $Entity): boolean;
        hurtTarget(arg0: $EntityHitResult): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        setupLength: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        length: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        earlyTerminate: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
    }
    export class $ItemLaserEntity extends $DanmakuLaserEntity implements $ItemSupplier {
        scale(): number;
        getItem(): $ItemStack;
        setItem(arg0: $ItemStack_): void;
        setDelayedMover(arg0: number, arg1: number, arg2: number, arg3: number): void;
        fullBright(): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        stack: $ItemStack;
        hasImpulse: boolean;
        setupLength: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        length: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        mover: $DanmakuMover;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        earlyTerminate: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$ItemLaserEntity>, arg1: $LivingEntity, arg2: $Level_);
        constructor(arg0: $EntityType_<$ItemLaserEntity>, arg1: number, arg2: number, arg3: number, arg4: $Level_);
        constructor(arg0: $EntityType_<$ItemLaserEntity>, arg1: $Level_);
    }
    export class $ItemBulletEntity extends $DanmakuBulletEntity implements $ItemSupplier {
        scale(): number;
        getItem(): $ItemStack;
        setItem(arg0: $ItemStack_): void;
        setControlCode(arg0: number): void;
        fullBright(): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        stack: $ItemStack;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        controlCode: number;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        mover: $DanmakuMover;
        zOld: number;
        afterExpiry: $TrailAction;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$ItemBulletEntity>, arg1: $LivingEntity, arg2: $Level_);
        constructor(arg0: $EntityType_<$ItemBulletEntity>, arg1: number, arg2: number, arg3: number, arg4: $Level_);
        constructor(arg0: $EntityType_<$ItemBulletEntity>, arg1: $Level_);
    }
    export class $DanmakuBulletEntity extends $BaseProjectile implements $IDanmakuEntity, $IEntityWithComplexSpawn {
        setup(arg0: number, arg1: number, arg2: boolean, arg3: boolean, arg4: $Vec3_): void;
        asTraceable(): $TraceableEntity;
        damage(arg0: $Entity): number;
        addAdditionalSaveData(arg0: $CompoundTag_): void;
        readAdditionalSaveData(arg0: $CompoundTag_): void;
        onHitEntity(arg0: $EntityHitResult): void;
        source(): $DamageSource;
        self(): $SimplifiedProjectile;
        shouldHurt(arg0: $Entity, arg1: $Entity): boolean;
        hurtTarget(arg0: $EntityHitResult): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
    }
}
