VersionLiteLoader:False
Info:正式版 1.21.1, NeoForge 21.1.230
VersionVanilla:21.0.1
LogoCustom:True
VersionVanillaName:1.21.1
ReleaseTime:2024-08-08 20:24
VersionNeoForge:21.1.230
Logo:PCL\Logo.png
VersionArgumentIndieV2:True
VersionArgumentIndie:1
State:7
VersionAdvanceJvm:-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:-UseAdaptiveSizePolicy -XX:+OmitStackTraceInFastThrow -XX:+PerfDisableSharedMem -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+OptimizeStringConcat -XX:+UseThreadPriorities -XX:+UseLoopPredicate -XX:-DontCompileHugeMethods -XX:+UseStringDeduplication -XX:MaxGCPauseMillis=37 -XX:G1HeapRegionSize=16M -XX:G1NewSizePercent=23 -XX:G1ReservePercent=20 -XX:SurvivorRatio=32 -XX:G1MixedGCCountTarget=3 -XX:G1HeapWastePercent=20 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:GCTimeRatio=99 -Dlog4j2.formatMsgNoLookups=true -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.readTimeout=600000 -Dfml.connectTimeout=600000