Info:正式版 1.21.1, NeoForge 21.1.233
IsStar:True
Logo:PCL\Logo.png
LogoCustom:True
ReleaseTime:2024-08-08 20:24
State:7
VersionAdvanceGC:4
VersionAdvanceJvm:-XX:+IgnoreUnrecognizedVMOptions -XX:+UnlockExperimentalVMOptions -Dfile.encoding=UTF-8 -Djava.awt.headless=true -XX:+AlwaysPreTouch -XX:+ExplicitGCInvokesConcurrent -XX:ReservedCodeCacheSize=384M -XX:+UseZGC -XX:+ZGenerational -XX:-ZProactive -XX:ZYoungCompactionLimit=20 -XX:ZFragmentationLimit=20 -XX:ZUncommitDelay=6 -XX:ZCollectionIntervalMinor=1.5 -XX:ZCollectionIntervalMajor=30.0 -XX:MaxDirectMemorySize=128G
VersionArgumentIndie:1
VersionArgumentIndieV2:True
VersionLiteLoader:False
VersionNeoForge:21.1.233
VersionVanilla:21.0.1
VersionVanillaName:1.21.1