import { $GoalSelector } from "@package/net/minecraft/world/entity/ai/goal";
import { $Ingredient } from "@package/net/minecraft/world/item/crafting";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $PortalProcessor, $Pose_, $EntityType, $Entity, $EntityDimensions, $ExperienceOrb, $TamableAnimal, $Entity$RemovalReason, $LivingEntity, $WalkAnimationState, $Mob } from "@package/net/minecraft/world/entity";
import { $ChatBubbleDataCollection, $ChatBubbleManager } from "@package/com/github/tartaricacid/touhoulittlemaid/entity/chatbubble";
import { $Activity } from "@package/net/minecraft/world/entity/schedule";
import { $MaidAIChatManager } from "@package/com/github/tartaricacid/touhoulittlemaid/ai/manager/entity";
import { $RandomSource } from "@package/net/minecraft/util";
import { $InteractionHand, $InteractionHand_ } from "@package/net/minecraft/world";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $RegistryFriendlyByteBuf, $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $TaskDataKey } from "@package/com/github/tartaricacid/touhoulittlemaid/api/entity/data";
import { $IMaidBackpack, $IBackpackData } from "@package/com/github/tartaricacid/touhoulittlemaid/api/backpack";
import { $ItemStack_, $ItemStack, $ItemCooldowns } from "@package/net/minecraft/world/item";
import { $Component_, $Component } from "@package/net/minecraft/network/chat";
import { $MobEffectInstance, $MobEffect } from "@package/net/minecraft/world/effect";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $AbstractArrow } from "@package/net/minecraft/world/entity/projectile";
import { $MaidFishingHook } from "@package/com/github/tartaricacid/touhoulittlemaid/entity/projectile";
import { $EntityHandsInvWrapper, $CombinedInvWrapper, $EntityArmorInvWrapper } from "@package/net/neoforged/neoforge/items/wrapper";
import { $MagicCastingAnimateState } from "@package/com/github/yimeng261/maidspell/client/animation";
import { $BaubleItemHandler } from "@package/com/github/tartaricacid/touhoulittlemaid/inventory/handler";
import { $CastingAnimateStateAccessor } from "@package/com/github/yimeng261/maidspell/client/spell";
import { $CrossbowAttackMob } from "@package/net/minecraft/world/entity/monster";
import { $Vec3, $AABB } from "@package/net/minecraft/world/phys";
import { $MaidSchedule, $MaidSchedule_ } from "@package/com/github/tartaricacid/touhoulittlemaid/entity/ai/brain";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $FavorabilityManager } from "@package/com/github/tartaricacid/touhoulittlemaid/entity/favorability";
import { $List, $List_, $Map } from "@package/java/util";
import { $MaidRenderState } from "@package/com/github/tartaricacid/touhoulittlemaid/api/client/render";
import { $IMaidTask } from "@package/com/github/tartaricacid/touhoulittlemaid/api/task";
import { $Predicate_ } from "@package/java/util/function";
import { $NodeEvaluator } from "@package/net/minecraft/world/level/pathfinder";
import { $Object2FloatOpenHashMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $ServerLevel } from "@package/net/minecraft/server/level";
import { $HolderLookup$Provider, $BlockPos, $Holder, $BlockPos_, $Direction_ } from "@package/net/minecraft/core";
import { $SendEffectPackage$EffectData_, $SendEffectPackage$EffectData } from "@package/com/github/tartaricacid/touhoulittlemaid/network/message";
import { $PathNavigation } from "@package/net/minecraft/world/entity/ai/navigation";
import { $Enum } from "@package/java/lang";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $ItemStackHandler } from "@package/net/neoforged/neoforge/items";
import { $ItemEntity } from "@package/net/minecraft/world/entity/item";
import { $IMaid } from "@package/com/github/tartaricacid/touhoulittlemaid/api/entity";
import { $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $ResourceLocation_, $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $EntityPowerPoint } from "@package/com/github/tartaricacid/touhoulittlemaid/entity/item";
import { $BaguAnimationController } from "@package/bagu_chan/bagus_lib/animation";
import { $AnchoredEntityMaid } from "@package/com/github/yimeng261/maidspell/api/entity";
import { $BlockEntity } from "@package/net/minecraft/world/level/block/entity";
import { $StreamCodec } from "@package/net/minecraft/network/codec";

declare module "@package/com/github/tartaricacid/touhoulittlemaid/entity/passive" {
    export class $MaidSwimManager {
        resetEatBreatheItem(): void;
        getSwimmingDimensions(): $EntityDimensions;
        updateSwimming(): void;
        isReadyToLand(): boolean;
        wantToSwim(): boolean;
        getSwimTarget(): $BlockPos;
        setWantToSwim(arg0: boolean): void;
        setSwimTarget(arg0: $BlockPos_): void;
        setReadyToLand(arg0: boolean): void;
        isGoingToBreath(): boolean;
        setGoingToBreath(arg0: boolean): void;
        isEatBreatheItem(): boolean;
        setEatBreatheItem(arg0: boolean): void;
        constructor(arg0: $EntityMaid);
        get swimmingDimensions(): $EntityDimensions;
    }
    export class $MaidNavigationManager {
        tick(): void;
        getEndPos(arg0: $PathNavigation): $BlockPos;
        isWaterSurface(arg0: $BlockPos_): boolean;
        getBasicNavigation(): $PathNavigation;
        getWaterNavigation(): $PathNavigation;
        resetNavigation(): void;
        constructor(arg0: $EntityMaid);
        get basicNavigation(): $PathNavigation;
        get waterNavigation(): $PathNavigation;
    }
    export class $MaidConfigManager$SyncNetwork {
        static decode(arg0: $FriendlyByteBuf): $MaidConfigManager$SyncNetwork;
        static encode(arg0: $MaidConfigManager$SyncNetwork, arg1: $FriendlyByteBuf): void;
        static handle(arg0: $MaidConfigManager$SyncNetwork, arg1: $EntityMaid): void;
        openFenceGate(): boolean;
        openDoor(): boolean;
        setOpenFenceGate(arg0: boolean): void;
        setShowBackpack(arg0: boolean): void;
        showBackpack(): boolean;
        setActiveClimbing(arg0: boolean): void;
        setOpenDoor(arg0: boolean): void;
        setPickType(arg0: $PickType_): void;
        showChatBubble(): boolean;
        setSoundFreq(arg0: number): void;
        activeClimbing(): boolean;
        setShowBackItem(arg0: boolean): void;
        showBackItem(): boolean;
        setShowChatBubble(arg0: boolean): void;
        pickType(): $PickType;
        soundFreq(): number;
        constructor(arg0: boolean, arg1: boolean, arg2: boolean, arg3: number, arg4: $PickType_, arg5: boolean, arg6: boolean, arg7: boolean);
    }
    export class $SchedulePos {
        load(arg0: $CompoundTag_, arg1: $EntityMaid): void;
        clear(arg0: $EntityMaid): void;
        save(arg0: $CompoundTag_): void;
        tick(arg0: $EntityMaid): void;
        isConfigured(): boolean;
        restrictTo(arg0: $EntityMaid): void;
        getDimension(): $ResourceLocation;
        getNearestPos(arg0: $EntityMaid): $BlockPos;
        getSleepPos(): $BlockPos;
        setHomeModeEnable(arg0: $EntityMaid, arg1: $BlockPos_): void;
        setConfigured(arg0: boolean): void;
        setDimension(arg0: $ResourceLocation_): void;
        setSleepPos(arg0: $BlockPos_): void;
        setWorkPos(arg0: $BlockPos_): void;
        setIdlePos(arg0: $BlockPos_): void;
        getWorkPos(): $BlockPos;
        getIdlePos(): $BlockPos;
        static SCHEDULE_POS_STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $SchedulePos>;
        constructor(arg0: $BlockPos_, arg1: $ResourceLocation_);
        constructor(arg0: $BlockPos_, arg1: $BlockPos_, arg2: $ResourceLocation_);
        constructor(arg0: $BlockPos_, arg1: $BlockPos_, arg2: $BlockPos_, arg3: $ResourceLocation_);
    }
    export class $MaidPathFindingBFS {
        find(arg0: $Predicate_<$BlockPos>): ($BlockPos) | undefined;
        finish(): void;
        canPathReach(arg0: $BlockPos_): boolean;
        constructor(arg0: $NodeEvaluator, arg1: $ServerLevel, arg2: $EntityMaid, arg3: $BlockPos_, arg4: number, arg5: number);
        constructor(arg0: $NodeEvaluator, arg1: $ServerLevel, arg2: $EntityMaid, arg3: number, arg4: number);
        constructor(arg0: $NodeEvaluator, arg1: $ServerLevel, arg2: $EntityMaid);
    }
    export class $MaidKillRecordManager {
        onTargetDeath(arg0: $EntityMaid, arg1: $LivingEntity): void;
        constructor();
    }
    export class $EntityMaid extends $TamableAnimal implements $CrossbowAttackMob, $IMaid, $AnchoredEntityMaid, $CastingAnimateStateAccessor {
        getData<T>(arg0: $TaskDataKey<T>): T;
        getTask(): $IMaidTask;
        getSchedule(): $MaidSchedule;
        setData<T>(arg0: $TaskDataKey<T>, arg1: T): void;
        getCooldowns(): $ItemCooldowns;
        canSee(arg0: $LivingEntity): boolean;
        getConfigManager(): $MaidConfigManager;
        static createAttributes(): $AttributeSupplier$Builder;
        getLuck(): number;
        canPickup(arg0: $Entity, arg1: boolean): boolean;
        canPickup(arg0: $Entity): boolean;
        tryPlayMaidPickupSound(): void;
        getFavorabilityManager(): $FavorabilityManager;
        getBackpackShowItem(): $ItemStack;
        maidSpell$setAnchored(arg0: boolean): void;
        spawnRankUpParticle(): void;
        spawnBubbleParticle(): void;
        onCrossbowAttackPerformed(): void;
        getGameRecordManager(): $MaidGameRecordManager;
        setStruckByLightning(arg0: boolean): void;
        isMaidInSittingPose(): boolean;
        getKillRecordManager(): $MaidKillRecordManager;
        setEntityInvulnerable(arg0: boolean): void;
        spawnExplosionParticle(): void;
        getNavigationManager(): $MaidNavigationManager;
        maidSpell$isAnchored(): boolean;
        memoryHandItemStack(arg0: $ItemStack_): void;
        getMaidBackpackType(): $IMaidBackpack;
        getHandItemsForAnimation(): $ItemStack[];
        getChatBubbleManager(): $ChatBubbleManager;
        setMaidBackpackType(arg0: $IMaidBackpack): void;
        spawnRestoreHealthParticle(arg0: number): void;
        dropResourcesToMaidInv(arg0: $BlockState_, arg1: $Level_, arg2: $BlockPos_, arg3: $BlockEntity, arg4: $EntityMaid, arg5: $ItemStack_): void;
        isStruckByLightning(): boolean;
        setBackpackShowItem(arg0: $ItemStack_): void;
        getAvailableBackpackInv(): $CombinedInvWrapper;
        setChargingCrossbow(arg0: boolean): void;
        spawnItemParticles(arg0: $ItemStack_, arg1: number): void;
        hurtAndBreak(arg0: $ItemStack_, arg1: number): void;
        getLeashOffset(): $Vec3;
        getBaseExperienceReward(): number;
        getDefaultDimensions(arg0: $Pose_): $EntityDimensions;
        getExperience(): number;
        maidspell$getCastingAnimateState(): $MagicCastingAnimateState;
        shouldLeaveMountOrSitForDanger(): boolean;
        getEffects(): $List<$SendEffectPackage$EffectData>;
        spawnHeartParticle(): void;
        getOrCreateData<T>(arg0: $TaskDataKey<T>, arg1: T): T;
        setAndSyncData<T>(arg0: $TaskDataKey<T>, arg1: T): void;
        refreshBrain(arg0: $ServerLevel): void;
        static getChatBubbleKey(): $EntityDataAccessor<$ChatBubbleDataCollection>;
        static canInsertItem(arg0: $ItemStack_): boolean;
        getIsInvulnerable(): boolean;
        pickupPowerPoint(arg0: $EntityPowerPoint): void;
        setSoundPackId(arg0: string): void;
        getSoundPackId(): string;
        setSchedule(arg0: $MaidSchedule_): void;
        getYsmModelName(): $Component;
        setFavorability(arg0: number): void;
        getYsmModelTexture(): string;
        setExperience(arg0: number): void;
        setIsYsmModel(arg0: boolean): void;
        getTamedItem(): $Ingredient;
        isStructureSpawn(): boolean;
        getFavorability(): number;
        canUseShield(): boolean;
        openMaidGui(arg0: $Player, arg1: number): boolean;
        openMaidGui(arg0: $Player): boolean;
        pickupXPOrb(arg0: $ExperienceOrb): void;
        getAvailableInv(arg0: boolean): $CombinedInvWrapper;
        getYsmModelId(): string;
        pickupArrow(arg0: $AbstractArrow, arg1: boolean): boolean;
        setBackpackFluid(arg0: string): void;
        canPathReach(arg0: $Entity): boolean;
        canPathReach(arg0: $BlockPos_): boolean;
        searchRadius(): number;
        isHomeModeEnable(): boolean;
        getScheduleDetail(): $Activity;
        setYsmModel(arg0: string, arg1: string, arg2: $Component_): void;
        backpackHasDelay(): boolean;
        playRouletteAnim(arg0: string): void;
        setHomeModeEnable(arg0: boolean): void;
        canBrainMoving(): boolean;
        setRideable(arg0: boolean): void;
        setBackpackDelay(): void;
        getSchedulePos(): $SchedulePos;
        getBackpackData(): $IBackpackData;
        stopRouletteAnim(): void;
        searchDimension(): $AABB;
        isSwingingArms(): boolean;
        setSwingingArms(arg0: boolean): void;
        getBrainSearchPos(): $BlockPos;
        getSwimManager(): $MaidSwimManager;
        getBackpackFluid(): string;
        getTemptationItem(): $Ingredient;
        setCanClimb(arg0: boolean): void;
        getHandsInvWrapper(): $EntityHandsInvWrapper;
        canPlaceBlock(arg0: $BlockPos_): boolean;
        setNavigation(arg0: $PathNavigation): void;
        asStrictMaid(): $EntityMaid;
        getArmorInvWrapper(): $EntityArmorInvWrapper;
        hasFishingHook(): boolean;
        getMaidBauble(): $BaubleItemHandler;
        teleportToOwner(arg0: $LivingEntity): boolean;
        placeItemBlock(arg0: $BlockPos_, arg1: $Direction_, arg2: $ItemStack_): boolean;
        placeItemBlock(arg0: $BlockPos_, arg1: $ItemStack_): boolean;
        placeItemBlock(arg0: $InteractionHand_, arg1: $BlockPos_, arg2: $Direction_, arg3: $ItemStack_): boolean;
        canDestroyBlock(arg0: $BlockPos_): boolean;
        getAiChatManager(): $MaidAIChatManager;
        destroyBlock(arg0: $Level_, arg1: $BlockPos_, arg2: boolean, arg3: $Entity): boolean;
        destroyBlock(arg0: $BlockPos_, arg1: boolean): boolean;
        destroyBlock(arg0: $BlockPos_): boolean;
        pickupItem(arg0: $ItemEntity, arg1: boolean): boolean;
        getAllInv(): $CombinedInvWrapper;
        isPickup(): boolean;
        getModelId(): string;
        isYsmModel(): boolean;
        getHunger(): number;
        setModelId(arg0: string): void;
        static getNtrItem(): $Ingredient;
        setTask(arg0: $IMaidTask): void;
        asEntity(): $Mob;
        getHideInv(): $ItemStackHandler;
        isAiming(): boolean;
        setHunger(arg0: number): void;
        setAiming(arg0: boolean): void;
        setEffects(arg0: $List_<$SendEffectPackage$EffectData_>): void;
        setBegging(arg0: boolean): void;
        isRideable(): boolean;
        setPickup(arg0: boolean): void;
        isBegging(): boolean;
        getTaskInv(): $ItemStackHandler;
        isCanClimb(): boolean;
        getMaidInv(): $ItemStackHandler;
        performRangedAttack(arg0: $LivingEntity, arg1: number): void;
        performCrossbowAttack(arg0: $LivingEntity, arg1: number): void;
        hasChestPlate(): boolean;
        hasLeggings(): boolean;
        /**
         * @deprecated
         */
        getAtBiomeTemp(): string;
        /**
         * @deprecated
         */
        hasSasimono(): boolean;
        hasBackpack(): boolean;
        /**
         * @deprecated
         */
        isSitInJoyBlock(): boolean;
        /**
         * @deprecated
         */
        getDim(): number;
        hasBoots(): boolean;
        onHurt(): boolean;
        hasHelmet(): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        static MAX_WEARING_ARMOR_CHANCE: number;
        static EXPERIENCE_TAG: string;
        static PRESERVE_ITEM_DROP_CHANCE_THRESHOLD: number;
        static DEFAULT_BASE_GRAVITY: number;
        static MAID_HIDE_INVENTORY_TAG: string;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        static MAX_PICKUP_LOOT_CHANCE: number;
        lootTable: $ResourceKey<$LootTable>;
        yHeadRot: number;
        noPhysics: boolean;
        yo: number;
        static TYPE: $EntityType<$EntityMaid>;
        yBodyRotO: number;
        removalReason: $Entity$RemovalReason;
        static YSM_ROAMING_UPDATE_FLAG_TAG: string;
        zza: number;
        static YSM_ROULETTE_ANIM_TAG: string;
        goalSelector: $GoalSelector;
        roamingVarsUpdateFlag: number;
        swingingArm: $InteractionHand;
        static ID_TAG: string;
        static DATA_HEALTH_ID: $EntityDataAccessor<number>;
        persistenceRequired: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        animationRecordTime: number;
        zo: number;
        static MAID_TASK_INVENTORY_TAG: string;
        walkDist: number;
        static YSM_MODEL_NAME_TAG: string;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        yya: number;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        hurtDuration: number;
        static TELEPORT_WHEN_DISTANCE_IS_SQ: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        dead: boolean;
        verticalCollision: boolean;
        verticalCollisionBelow: boolean;
        static DEFAULT_BABY_SCALE: number;
        eyeHeight: number;
        static ATTRIBUTES_FIELD: string;
        rouletteAnim: string;
        static UPDATE_GOAL_SELECTOR_EVERY_N_TICKS: number;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        flyDist: number;
        static PASSENGERS_TAG: string;
        static MAID_INVENTORY_TAG: string;
        static YSM_MODEL_ID_TAG: string;
        wasOnFire: boolean;
        attackAnim: number;
        zOld: number;
        handItemsForAnimation: $ItemStack[];
        rouletteAnimPlaying: boolean;
        static BABY_START_AGE: number;
        timeOffs: number;
        static MAID_BAUBLE_INVENTORY_TAG: string;
        wasTouchingWater: boolean;
        activeEffects: $Map<$Holder<$MobEffect>, $MobEffectInstance>;
        rotA: number;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        guiOpening: boolean;
        static DEFAULT_EQUIPMENT_DROP_CHANCE: number;
        static ARMOR_SLOT_OFFSET: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        roamingVars: $Object2FloatOpenHashMap<string>;
        tickCount: number;
        static MAX_ENCHANTED_ARMOR_CHANCE: number;
        static MAX_ENCHANTED_WEAPON_CHANCE: number;
        static BOARDING_COOLDOWN: number;
        static PRESERVE_ITEM_DROP_CHANCE: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        level: $Level;
        ambientSoundTime: number;
        static YSM_MODEL_TEXTURE_TAG: string;
        moveDist: number;
        static MAID_BACKPACK_TYPE: string;
        rouletteAnimDirty: boolean;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static IS_YSM_MODEL_TAG: string;
        targetSelector: $GoalSelector;
        xOld: number;
        wasInPowderSnow: boolean;
        hurtTime: number;
        xpReward: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        deathTime: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        jumping: boolean;
        static SOUND_PACK_ID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static YSM_ROAMING_VARS_TAG: string;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        renderState: $MaidRenderState;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        random: $RandomSource;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        fishing: $MaidFishingHook;
        removeArrowTime: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static BAUBLE_INV_SIZE: number;
        animationId: number;
        yBodyRot: number;
        blocksBuilding: boolean;
        static MODEL_ID_TAG: string;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        invulnerableDuration: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        shouldReset: boolean;
        effectsDirty: boolean;
        constructor(arg0: $Level_);
        get cooldowns(): $ItemCooldowns;
        get configManager(): $MaidConfigManager;
        get luck(): number;
        get favorabilityManager(): $FavorabilityManager;
        get gameRecordManager(): $MaidGameRecordManager;
        get maidInSittingPose(): boolean;
        get killRecordManager(): $MaidKillRecordManager;
        set entityInvulnerable(value: boolean);
        get navigationManager(): $MaidNavigationManager;
        get chatBubbleManager(): $ChatBubbleManager;
        get availableBackpackInv(): $CombinedInvWrapper;
        set chargingCrossbow(value: boolean);
        get leashOffset(): $Vec3;
        get baseExperienceReward(): number;
        static get chatBubbleKey(): $EntityDataAccessor<$ChatBubbleDataCollection>;
        get ysmModelName(): $Component;
        get ysmModelTexture(): string;
        get tamedItem(): $Ingredient;
        get structureSpawn(): boolean;
        get ysmModelId(): string;
        get scheduleDetail(): $Activity;
        get schedulePos(): $SchedulePos;
        get backpackData(): $IBackpackData;
        get brainSearchPos(): $BlockPos;
        get swimManager(): $MaidSwimManager;
        get temptationItem(): $Ingredient;
        get handsInvWrapper(): $EntityHandsInvWrapper;
        set navigation(value: $PathNavigation);
        get armorInvWrapper(): $EntityArmorInvWrapper;
        get maidBauble(): $BaubleItemHandler;
        get aiChatManager(): $MaidAIChatManager;
        get allInv(): $CombinedInvWrapper;
        static get ntrItem(): $Ingredient;
        get hideInv(): $ItemStackHandler;
        get taskInv(): $ItemStackHandler;
        get maidInv(): $ItemStackHandler;
        get atBiomeTemp(): string;
        get sitInJoyBlock(): boolean;
        get dim(): number;
    }
    export class $MaidGameRecordManager {
        resetStatue(): void;
        getGomokuWinCount(): number;
        markStatue(arg0: boolean): void;
        increaseGomokuWinCount(): void;
        isWin(): boolean;
        isLost(): boolean;
        constructor(arg0: $EntityMaid);
        get gomokuWinCount(): number;
        get win(): boolean;
        get lost(): boolean;
    }
    export class $PickType extends $Enum<$PickType> {
        static values(): $PickType[];
        static valueOf(arg0: string): $PickType;
        canPickItem(): boolean;
        canPickXp(): boolean;
        static getPreviousPickType(arg0: $PickType_): $PickType;
        static getNextPickType(arg0: $PickType_): $PickType;
        static getTransKey(arg0: $PickType_): string;
        static ALL: $PickType;
        static ONLY_XP: $PickType;
        static ONLY_ITEM: $PickType;
    }
    /**
     * Values that may be interpreted as {@link $PickType}.
     */
    export type $PickType_ = "only_item" | "only_xp" | "all";
    export class $MaidConfigManager {
        getSoundFreq(): number;
        getPickupType(): $PickType;
        isOpenDoor(): boolean;
        setOpenFenceGate(arg0: boolean): void;
        setShowBackpack(arg0: boolean): void;
        setActiveClimbing(arg0: boolean): void;
        setOpenDoor(arg0: boolean): void;
        getSyncNetwork(): $MaidConfigManager$SyncNetwork;
        setSoundFreq(arg0: number): void;
        setShowBackItem(arg0: boolean): void;
        isShowBackpack(): boolean;
        isChatBubbleShow(): boolean;
        isShowBackItem(): boolean;
        isActiveClimbing(): boolean;
        setPickupType(arg0: $PickType_): void;
        setChatBubbleShow(arg0: boolean): void;
        isOpenFenceGate(): boolean;
        get syncNetwork(): $MaidConfigManager$SyncNetwork;
    }
}
