import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $Self, $ItemRenderable } from "@package/io/github/forgestove/create_cyber_goggles/core/api";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $LivingEntity, $PortalProcessor, $Entity, $TraceableEntity } from "@package/net/minecraft/world/entity";
import { $CallbackInfo, $CallbackInfoReturnable } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $FallingBlockEntityAccessor } from "@package/com/simibubi/create/foundation/mixin/accessor";
import { $UUID, $List, $UUID_ } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $Predicate_ } from "@package/java/util/function";
import { $HolderLookup$Provider, $BlockPos, $BlockPos_ } from "@package/net/minecraft/core";
import { $BlockState_, $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $Block_ } from "@package/net/minecraft/world/level/block";
import { $ItemEntityKJS } from "@package/dev/latvian/mods/kubejs/core";
import { $Object } from "@package/java/lang";
import { $AccessorMixinFallingBlockEntity } from "@package/noobanidus/mods/lootr/common/mixin/accessor";
import { $BaguAnimationController } from "@package/bagu_chan/bagus_lib/animation";
import { $DamageSource_ } from "@package/net/minecraft/world/damagesource";
import { $ItemEntityExtensions } from "@package/artifacts/extensions/mobeffect/magnetism";

declare module "@package/net/minecraft/world/entity/item" {
    export class $ItemEntity extends $Entity implements $TraceableEntity, $ItemRenderable, $Self<any>, $ItemEntityKJS, $ItemEntityExtensions {
        static merge(arg0: $ItemStack_, arg1: $ItemStack_, arg2: number): $ItemStack;
        copy(): $ItemEntity;
        getTarget(): $UUID;
        setTarget(arg0: $UUID_): void;
        getOwner(): $Entity;
        getItem(): $ItemStack;
        getAge(): number;
        setPickUpDelay(arg0: number): void;
        setItem(arg0: $ItemStack_): void;
        setDefaultPickUpDelay(): void;
        handler$gcf000$l2complements$l2complments_hurt_itemBurnt(arg0: $DamageSource_, arg1: number, arg2: $CallbackInfoReturnable<any>): void;
        setThrower(arg0: $Entity): void;
        getSpin(arg0: number): number;
        static areMergable(arg0: $ItemStack_, arg1: $ItemStack_): boolean;
        setNeverPickUp(): void;
        setNoPickUpDelay(): void;
        ccg$getItemStack(): $ItemStack;
        hasPickUpDelay(): boolean;
        makeFakeItem(): void;
        setUnlimitedLifetime(): void;
        setExtendedLifetime(): void;
        artifacts$wasThrownBy(entity: $LivingEntity): boolean;
        addAdditionalSaveData(arg0: $CompoundTag_): void;
        readAdditionalSaveData(arg0: $CompoundTag_): void;
        artifacts$setThrower(entity: $LivingEntity): void;
        handler$gcf000$l2complements$dampensVibrations_sculkiumMinedItem(arg0: $CallbackInfoReturnable<any>): void;
        thiz(): $Object;
        setLifespan(lifespan: number): void;
        setNoDespawn(): void;
        getLifespan(): number;
        setDefaultPickUpDelay(): void;
        setNoPickUpDelay(): void;
        getTicksUntilDespawn(): number;
        setTicksUntilDespawn(ticks: number): void;
        setInfinitePickUpDelay(): void;
        serializeNBT(arg0: $HolderLookup$Provider): $Object;
        lifespan: number;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static EYE_HEIGHT: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        static INFINITE_PICKUP_DELAY: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static LIFETIME: number;
        bobOffs: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        pickupDelay: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        age: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$ItemEntity>, arg1: $Level_);
        constructor(arg0: $Level_, arg1: number, arg2: number, arg3: number, arg4: $ItemStack_);
        constructor(arg0: $Level_, arg1: number, arg2: number, arg3: number, arg4: $ItemStack_, arg5: number, arg6: number, arg7: number);
        get owner(): $Entity;
        set pickUpDelay(value: number);
        set thrower(value: $Entity);
    }
    export class $PrimedTnt extends $Entity implements $TraceableEntity {
        getOwner(): $LivingEntity;
        getBlockState(): $BlockState;
        setBlockState(arg0: $BlockState_): void;
        setFuse(arg0: number): void;
        getFuse(): number;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static TAG_FUSE: string;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$PrimedTnt>, arg1: $Level_);
        constructor(arg0: $Level_, arg1: number, arg2: number, arg3: number, arg4: $LivingEntity);
        get owner(): $LivingEntity;
    }
    export class $FallingBlockEntity extends $Entity implements $AccessorMixinFallingBlockEntity, $FallingBlockEntityAccessor {
        getBlockState(): $BlockState;
        modify$bnd000$supplementaries$supp$concreteFix(arg0: $BlockPos_): $BlockPos;
        disableDrop(): void;
        setBlockState(state: $BlockState_): void;
        setHurtsEntities(arg0: number, arg1: number): void;
        setStartPos(arg0: $BlockPos_): void;
        getStartPos(): $BlockPos;
        static callInit$create_$md$70d283$0(arg0: $Level_, arg1: number, arg2: number, arg3: number, arg4: $BlockState_): $FallingBlockEntity;
        handler$glf000$architectury$handleLand(ci: $CallbackInfo, block: $Block_, blockPos2: $BlockPos_, bl: boolean, bl2: boolean, d: number, blockState: $BlockState_): void;
        handler$hha000$quark$stopTickingIfRemoved(arg0: $CallbackInfo): void;
        handler$ijk000$bakeries$causeFallDamage(arg0: number, arg1: number, arg2: $DamageSource_, arg3: $CallbackInfoReturnable<any>, arg4: number, arg5: $Predicate_<any>, arg6: $DamageSource_, arg7: number, arg8: $Block_): void;
        callOnBrokenAfterFall(arg0: $Block_, arg1: $BlockPos_): void;
        static fall(arg0: $Level_, arg1: $BlockPos_, arg2: $BlockState_): $FallingBlockEntity;
        dropAsItem(arg0: $BlockState_, arg1: $CompoundTag_, arg2: $Level_): $List<any>;
        lootr$setBlockState(arg0: $BlockState_): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        blockState: $BlockState;
        cancelDrop: boolean;
        hasImpulse: boolean;
        dropItem: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        blockData: $CompoundTag;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        forceTickAfterTeleportToDuplicate: boolean;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        time: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$FallingBlockEntity>, arg1: $Level_);
        constructor(arg0: $Level_, arg1: number, arg2: number, arg3: number, arg4: $BlockState_);
    }
}
