import { $Level_, $Level } from "@package/net/minecraft/world/level";
import { $ItemStack, $ItemStack_ } from "@package/net/minecraft/world/item";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $IEntityWithComplexSpawn } from "@package/net/neoforged/neoforge/entity";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $Entity, $EntityType$Builder, $PortalProcessor } from "@package/net/minecraft/world/entity";
import { $AbstractHurtingProjectile } from "@package/net/minecraft/world/entity/projectile";
import { $UUID } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $HolderLookup$Provider, $BlockPos } from "@package/net/minecraft/core";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $BaguAnimationController } from "@package/bagu_chan/bagus_lib/animation";
import { $PotatoCannonProjectileType, $PotatoProjectileRenderMode } from "@package/com/simibubi/create/api/equipment/potatoCannon";
import { $Vec3_ } from "@package/net/minecraft/world/phys";

declare module "@package/com/simibubi/create/content/equipment/potatoCannon" {
    export class $PotatoProjectileEntity extends $AbstractHurtingProjectile implements $IEntityWithComplexSpawn {
        static build(arg0: $EntityType$Builder<never>): $EntityType$Builder<never>;
        getItem(): $ItemStack;
        setItem(arg0: $ItemStack_): void;
        setEnchantmentEffectsFromCannon(arg0: $ItemStack_): void;
        static playHitSound(arg0: $Level_, arg1: $Vec3_): void;
        writeSpawnData(arg0: $RegistryFriendlyByteBuf): void;
        readSpawnData(arg0: $RegistryFriendlyByteBuf): void;
        getRenderMode(): $PotatoProjectileRenderMode;
        static playLaunchSound(arg0: $Level_, arg1: $Vec3_, arg2: number): void;
        setStuckEntity(arg0: $Entity): void;
        getProjectileType(): $PotatoCannonProjectileType;
        getStuckEntity(): $Entity;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        leftOwner: boolean;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        accelerationPower: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        static INITAL_ACCELERATION_POWER: number;
        random: $RandomSource;
        static DEFLECTION_SCALE: number;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        ownerUUID: $UUID;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        hasBeenShot: boolean;
        cachedOwner: $Entity;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$AbstractHurtingProjectile>, arg1: $Level_);
        set enchantmentEffectsFromCannon(value: $ItemStack_);
        get renderMode(): $PotatoProjectileRenderMode;
        get projectileType(): $PotatoCannonProjectileType;
    }
}
