ItemEvents.modifyTooltips(event => {
  //绿色字为补充物品的额外用法
  event.add('minecraft:golden_sword', Text.translate('kubejs.tooltip.item.minecraft.golden_sword.0'))
  event.add('chimes:bamboo_chimes', Text.translate('kubejs.tooltip.item.chimes.bamboo_chimes.0'))
  event.add('chimes:iron_chimes', Text.translate('kubejs.tooltip.item.chimes.iron_chimes.0'))
  event.add('chimes:carved_bamboo_chimes', Text.translate('kubejs.tooltip.item.chimes.carved_bamboo_chimes.0'))
  event.add('chimes:copper_chimes', Text.translate('kubejs.tooltip.item.chimes.copper_chimes.0'))
  event.add('chimes:amethyst_chimes', Text.translate('kubejs.tooltip.item.chimes.amethyst_chimes.0'))
  event.add('chimes:glass_bells', Text.translate('kubejs.tooltip.item.chimes.glass_bells.0'))
  event.add('minecraft:anvil', Text.translate('kubejs.tooltip.item.minecraft.anvil.0'))
  event.add('minecraft:damaged_anvil', Text.translate('kubejs.tooltip.item.minecraft.damaged_anvil.0'))
  event.add('minecraft:chipped_anvil', Text.translate('kubejs.tooltip.item.minecraft.chipped_anvil.0'))
  event.add('quark:grate', Text.translate('kubejs.tooltip.item.quark.grate.0'))
  event.add('quark:bottled_cloud', [Text.translate('kubejs.tooltip.item.quark.bottled_cloud.0'), Text.translate('kubejs.tooltip.item.quark.bottled_cloud.1'), Text.translate('kubejs.tooltip.item.quark.bottled_cloud.2')])
  event.add('quark:chute', [Text.translate('kubejs.tooltip.item.quark.chute.0'), Text.translate('kubejs.tooltip.item.quark.chute.1')])
  event.add('quark:feeding_trough', Text.translate('kubejs.tooltip.item.quark.feeding_trough.0'))
  event.add('quark:soul_bead', Text.translate('kubejs.tooltip.item.quark.soul_bead.0'))
  event.add('quark:seed_pouch', [Text.translate('kubejs.tooltip.item.quark.seed_pouch.0'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.1'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.2'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.3'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.4'), Text.translate('kubejs.tooltip.item.quark.seed_pouch.5')])
  event.add('quark:gravisand', Text.translate('kubejs.tooltip.item.quark.gravisand.0'))
  event.add('quark:ancient_tome', [Text.translate('kubejs.tooltip.item.quark.ancient_tome.0'), Text.translate('kubejs.tooltip.item.quark.ancient_tome.1'), Text.translate('kubejs.tooltip.item.quark.ancient_tome.2')])
  event.add('supplementaries:key', Text.translate('kubejs.tooltip.item.supplementaries.key.0'))
  event.add('supplementaries:flute', [Text.translate('kubejs.tooltip.item.supplementaries.flute.0'), Text.translate('kubejs.tooltip.item.supplementaries.flute.1'), Text.translate('kubejs.tooltip.item.supplementaries.flute.2')])
  event.add('supplementaries:antique_ink', Text.translate('kubejs.tooltip.item.supplementaries.antique_ink.0'))
  event.add('supplementaries:cog_block', Text.translate('kubejs.tooltip.item.supplementaries.cog_block.0'))
  event.add('quark:trowel', Text.translate('kubejs.tooltip.item.quark.trowel.0'))
  event.add('minecraft:torch', Text.translate('kubejs.tooltip.item.minecraft.torch.0'))
  event.add('l2complements:eternium_hoe', Text.translate('kubejs.tooltip.item.l2complements.eternium_hoe.0'))
  event.add('tofucraft:bottle_soyoil', Text.translate('kubejs.tooltip.item.tofucraft.bottle_soyoil.0'))
  //黄色字为作者的个人吐槽
  event.add('minecraft:diorite', [Text.translate('kubejs.tooltip.item.minecraft.diorite.0'), Text.translate('kubejs.tooltip.item.minecraft.diorite.1')])
  event.add('irons_spellbooks:keeper_flamberge', Text.translate('kubejs.tooltip.item.irons_spellbooks.keeper_flamberge.0'))
  event.add('minecraft:iron_helmet', Text.translate('kubejs.tooltip.item.minecraft.iron_helmet.0'))
  event.add('fruitsdelight:bayberry', Text.translate('kubejs.tooltip.item.fruitsdelight.bayberry.0'))
  event.add('fruitsdelight:lychee', Text.translate('kubejs.tooltip.item.fruitsdelight.lychee.0'))
  event.add('fruitsdelight:durian', Text.translate('kubejs.tooltip.item.fruitsdelight.durian.0'))
  event.add('fruitsdelight:baked_durian', Text.translate('kubejs.tooltip.item.fruitsdelight.baked_durian.0'))
  event.add('fruitsdelight:kiwi', Text.translate('kubejs.tooltip.item.fruitsdelight.kiwi.0'))
  event.add('fruitsdelight:peach', Text.translate('kubejs.tooltip.item.fruitsdelight.peach.0'))
  event.add('fruitsdelight:pineapple', Text.translate('kubejs.tooltip.item.fruitsdelight.pineapple.0'))
  event.add('fruitsdelight:lemon', Text.translate('kubejs.tooltip.item.fruitsdelight.lemon.0'))
  event.add('vintagedelight:kimchi', Text.translate('kubejs.tooltip.item.vintagedelight.kimchi.0'))
  event.add('vintagedelight:century_egg', Text.translate('kubejs.tooltip.item.vintagedelight.century_egg.0'))
  event.add('vintagedelight:pickled_egg', Text.translate('kubejs.tooltip.item.vintagedelight.pickled_egg.0'))
  event.add('vintagedelight:pickle', Text.translate('kubejs.tooltip.item.vintagedelight.pickle.0'))
  event.add('vintagedelight:peanut', Text.translate('kubejs.tooltip.item.vintagedelight.peanut.0'))
  event.add('youkaishomecoming:raw_lamprey', Text.translate('kubejs.tooltip.item.youkaishomecoming.raw_lamprey.0'))
  event.add('youkaishomecoming:raw_lamprey_fillet', Text.translate('kubejs.tooltip.item.youkaishomecoming.raw_lamprey_fillet.0'))
  event.add('youkaishomecoming:chest_of_heart_throbbing_surprise', [Text.translate('kubejs.tooltip.item.youkaishomecoming.chest_of_heart_throbbing_surprise.0'), Text.translate('kubejs.tooltip.item.youkaishomecoming.chest_of_heart_throbbing_surprise.1'), Text.translate('kubejs.tooltip.item.youkaishomecoming.chest_of_heart_throbbing_surprise.2')])
  event.add('youkaishomecoming:oily_bean_curd', Text.translate('kubejs.tooltip.item.youkaishomecoming.oily_bean_curd.0'))
  event.add('youkaishomecoming:udumbara_flower', [Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.0'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.1'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.2'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.3'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.4'), Text.translate('kubejs.tooltip.item.youkaishomecoming.udumbara_flower.5')])
  event.add('minecraft:cooked_beef', Text.translate('kubejs.tooltip.item.minecraft.cooked_beef.0'))
  event.add('youkaishomecoming:roe', Text.translate('kubejs.tooltip.item.youkaishomecoming.roe.0'))
  event.add('fruitsdelight:persimmon', [Text.translate('kubejs.tooltip.item.fruitsdelight.persimmon.0'), Text.translate('kubejs.tooltip.item.fruitsdelight.persimmon.1')])
  event.add('fruitsdelight:cranberry', Text.translate('kubejs.tooltip.item.fruitsdelight.cranberry.0'))
  event.add('ends_delight:end_mixed_salad', Text.translate('kubejs.tooltip.item.ends_delight.end_mixed_salad.0'))
  event.add('ends_delight:assorted_salad', Text.translate('kubejs.tooltip.item.ends_delight.assorted_salad.0'))
  event.add('farmersdelight:fruit_salad', Text.translate('kubejs.tooltip.item.farmersdelight.fruit_salad.0'))
  event.add('farmersdelight:mixed_salad', Text.translate('kubejs.tooltip.item.farmersdelight.mixed_salad.0'))
  event.add('farmersdelight:nether_salad', Text.translate('kubejs.tooltip.item.farmersdelight.nether_salad.0'))
  event.add('vintagedelight:cucumber_salad', Text.translate('kubejs.tooltip.item.vintagedelight.cucumber_salad.0'))
  event.add('bakeries:baguette', Text.translate('kubejs.tooltip.item.bakeries.baguette.0'))
  event.add('artifacts:everlasting_beef', [Text.translate('kubejs.tooltip.item.artifacts.everlasting_beef.0'), Text.translate('kubejs.tooltip.item.artifacts.everlasting_beef.1')])
  event.add('artifacts:eternal_steak', [Text.translate('kubejs.tooltip.item.artifacts.eternal_steak.0'), Text.translate('kubejs.tooltip.item.artifacts.eternal_steak.1')])
  event.add('youkaishomecoming:green_coffee_bean', Text.translate('kubejs.tooltip.item.youkaishomecoming.green_coffee_bean.0'))
  event.add('youkaishomecoming:coffee_beans', Text.translate('kubejs.tooltip.item.youkaishomecoming.coffee_beans.0'))
  event.add('youkaishomecoming:coffee_powder', Text.translate('kubejs.tooltip.item.youkaishomecoming.coffee_powder.0'))
  event.add('bakeries:raw_coffee_bean', Text.translate('kubejs.tooltip.item.bakeries.raw_coffee_bean.0'))
  event.add('bakeries:coffee_bean', Text.translate('kubejs.tooltip.item.bakeries.coffee_bean.0'))
  event.add('bakeries:ground_coffee', Text.translate('kubejs.tooltip.item.bakeries.ground_coffee.0'))
  //为标签添加的物品吐槽
  event.add('#c:pasta', Text.translate('kubejs.tooltip.tag.c.pasta.0'))
  event.add('#c:chocolate', Text.translate('kubejs.tooltip.tag.c.chocolate.0'))
  event.add('#c:fruits/passion_fruit', Text.translate('kubejs.tooltip.tag.c.fruits.passion_fruit.0'))
  event.add('#c:fruits/raspberries', Text.translate('kubejs.tooltip.tag.c.fruits.raspberries.0'))
  event.add('#c:fruits/lemon', Text.translate('kubejs.tooltip.tag.c.fruits.lemon.0'))
  event.add('#c:fruits/blueberry', Text.translate('kubejs.tooltip.tag.c.fruits.blueberry.0'))
  event.add('#c:fruits/mango', Text.translate('kubejs.tooltip.tag.c.fruits.mango.0'))
  event.add('#c:fruits/peach', Text.translate('kubejs.tooltip.tag.c.fruits.peach.0'))
  event.add('#c:fruits/pineapple', Text.translate('kubejs.tooltip.tag.c.fruits.pineapple.0'))
  event.add('#c:fruits/cranberry', Text.translate('kubejs.tooltip.tag.c.fruits.cranberry.0'))
  event.add('#c:fruits/orange', Text.translate('kubejs.tooltip.tag.c.fruits.orange.0'))
  event.add('#c:fruits/lychee', Text.translate('kubejs.tooltip.tag.c.fruits.lychee.0'))
  event.add('#c:fruits/strawberry', Text.translate('kubejs.tooltip.tag.c.fruits.strawberry.0'))
  event.add('#c:fruits/hamimelon', Text.translate('kubejs.tooltip.tag.c.fruits.hamimelon.0'))
  event.add('#c:fruits/grapes', Text.translate('kubejs.tooltip.tag.c.fruits.grapes.0'))
  event.add('#c:fruits/persimmon', Text.translate('kubejs.tooltip.tag.c.fruits.persimmon.0'))
  event.add('#c:fruits/watermelon', Text.translate('kubejs.tooltip.tag.c.fruits.watermelon.0'))
  event.add('#c:fruits/coconut', Text.translate('kubejs.tooltip.tag.c.fruits.coconut.0'))
  event.add('#c:vegetables/onion', Text.translate('kubejs.tooltip.tag.c.vegetables.onion.0'))
  event.add('#c:vegetables/tomato', Text.translate('kubejs.tooltip.tag.c.vegetables.tomato.0'))
  event.add('#c:vegetables/chili_pepper', Text.translate('kubejs.tooltip.tag.c.vegetables.chili_pepper.0'))
  event.add('#c:crops/olives', Text.translate('kubejs.tooltip.tag.c.crops.olives.0'))
  event.add('#c:crops/adzuki', Text.translate('kubejs.tooltip.tag.c.crops.adzuki.0'))
  event.add('#c:crops/corn', Text.translate('kubejs.tooltip.tag.c.crops.corn.0'))
  event.add('#c:crops/dragon_fruit', Text.translate('kubejs.tooltip.tag.c.crops.dragon_fruit.0'))
  event.add('#c:crops/apple', Text.translate('kubejs.tooltip.tag.c.crops.apple.0'))
  event.add('#c:crops/yucca', Text.translate('kubejs.tooltip.tag.c.crops.yucca.0'))
  event.add('#c:crops/currant', Text.translate('kubejs.tooltip.tag.c.crops.currant.0'))
  event.add('#c:crops/hawberry', Text.translate('kubejs.tooltip.tag.c.crops.hawberry.0'))
  event.add('#c:crops/pear', Text.translate('kubejs.tooltip.tag.c.crops.pear.0'))
  event.add('#c:crops/rice', Text.translate('kubejs.tooltip.tag.c.crops.rice.0'))
  event.add('#c:crops/mint', Text.translate('kubejs.tooltip.tag.c.crops.mint.0'))
  event.add('#c:crops/aloe', Text.translate('kubejs.tooltip.tag.c.crops.aloe.0'))
  event.add('#c:crops/carrot', Text.translate('kubejs.tooltip.tag.c.crops.carrot.0'))
  event.add('#c:crops/potato', Text.translate('kubejs.tooltip.tag.c.crops.potato.0'))
  event.add('#c:crops/beetroot', Text.translate('kubejs.tooltip.tag.c.crops.beetroot.0'))
  event.add('#c:crops/leek', Text.translate('kubejs.tooltip.tag.c.crops.leek.0'))
  event.add('#c:crops/peanut', Text.translate('kubejs.tooltip.tag.c.crops.peanut.0'))
  event.add('#c:crops/cabbage', Text.translate('kubejs.tooltip.tag.c.crops.cabbage.0'))
  event.add('#c:crops/cucumber', Text.translate('kubejs.tooltip.tag.c.crops.cucumber.0'))
  event.add('#c:crops/barley', Text.translate('kubejs.tooltip.tag.c.crops.barley.0'))
  event.add('#c:crops/oat', Text.translate('kubejs.tooltip.tag.c.crops.oat.0'))
  // Majobroom
  event.add('majobroom:broom', [Text.translate('kubejs.tooltip.item.majobroom.broom.0'), Text.translate('kubejs.tooltip.item.majobroom.broom.1')])
  event.add('majobroom:majo_hat', Text.translate('kubejs.tooltip.item.majobroom.majo_hat.0'))
  event.add('majobroom:majo_cloth', Text.translate('kubejs.tooltip.item.majobroom.majo_cloth.0'))
  event.add('majobroom:majo_stocking', Text.translate('kubejs.tooltip.item.majobroom.majo_stocking.0'))
  event.add('majobroom:majo_boots', Text.translate('kubejs.tooltip.item.majobroom.majo_boots.0'))
  //红色字为禁用物品或危险物品的提示讯息
  event.add('minecraft:enchanting_table', [Text.translate('kubejs.tooltip.item.minecraft.enchanting_table.0'), Text.translate('kubejs.tooltip.item.minecraft.enchanting_table.1')])
  event.add('l2complements:diffusion_wand', Text.translate('kubejs.tooltip.item.l2complements.diffusion_wand.0'))
  event.add('create_sa:block_picker', Text.translate('kubejs.tooltip.item.create_sa.block_picker.0'))
  // Eggs
  //event.add('create:crushing_wheel', Text.translate('kubejs.tooltip.item.create.crushing_wheel.0'))
})