import { $TagKey, $TagKey_ } from "@package/net/minecraft/tags";
import { $LongType, $EnergyType } from "@package/com/wintercogs/beyonddimensions/api/longtype";
import { $MapCodec, $Codec } from "@package/com/mojang/serialization";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $IStackKey, $IStackRender, $KeyAmount } from "@package/com/wintercogs/beyonddimensions/api/storage/key";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $FluidStack_, $FluidStack } from "@package/net/neoforged/neoforge/fluids";
import { $HolderLookup$Provider } from "@package/net/minecraft/core";
import { $Stream } from "@package/java/util/stream";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $ResourceLocation } from "@package/net/minecraft/resources";
import { $DataComponentPatch_ } from "@package/net/minecraft/core/component";
import { $Object, $Class } from "@package/java/lang";

declare module "@package/com/wintercogs/beyonddimensions/api/storage/key/impl" {
    export class $LongStackKey<T extends $LongType<T>> implements $IStackKey<T> {
        isEmpty(): boolean;
        isSame(arg0: $IStackKey<never>): boolean;
        getTypeID(): $ResourceLocation;
        copyStack(): T;
        getTypeId(): $ResourceLocation;
        getStackClass(): $Class<T>;
        copyStackWithCount(arg0: number): T;
        getRenderStack(): T;
        getSourceClass(): $Class<never>;
        getVanillaMaxStackSize(): number;
        isSameTypeSameComponents(arg0: $IStackKey<never>): boolean;
        getCustomMaxStackSize(): number;
        getReadOnlyStack(): T;
        constructor();
        get empty(): boolean;
        get typeID(): $ResourceLocation;
        get typeId(): $ResourceLocation;
        get stackClass(): $Class<T>;
        get renderStack(): T;
        get sourceClass(): $Class<never>;
        get vanillaMaxStackSize(): number;
        get customMaxStackSize(): number;
        get readOnlyStack(): T;
    }
    export class $ItemStackKey implements $IStackKey<$ItemStack> {
        isEmpty(): boolean;
        serialize(arg0: $RegistryFriendlyByteBuf): void;
        getModId(): string;
        hasTag(arg0: $TagKey_<never>): boolean;
        getTags(): $Stream<$TagKey<never>>;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        deserializeNBT(arg0: $CompoundTag_, arg1: $HolderLookup$Provider): $ItemStackKey;
        codec(): $MapCodec<$ItemStackKey>;
        isSame(arg0: $IStackKey<never>): boolean;
        getTypeId(): $ResourceLocation;
        getStackClass(): $Class<$ItemStack>;
        copyStackWithCount(arg0: number): $ItemStack;
        getSourceClass(): $Class<never>;
        fromStackObject(arg0: $Object): $KeyAmount;
        getRender(): $IStackRender;
        getVanillaMaxStackSize(): number;
        isSameTypeSameComponents(arg0: $IStackKey<never>): boolean;
        getCustomMaxStackSize(): number;
        getSource(): $Object;
        deserialize(arg0: $RegistryFriendlyByteBuf): $IStackKey<$ItemStack>;
        getEmpty(): $IStackKey<$ItemStack>;
        copyStack(): $ItemStack;
        getReadOnlyStack(): $ItemStack;
        fromSourceObject(arg0: $Object, arg1: $DataComponentPatch_): $IStackKey<$ItemStack>;
        getRenderStack(): $ItemStack;
        getEmptyStack(): $ItemStack;
        static TYPE_CODEC: $MapCodec<$ItemStackKey>;
        static CODEC: $Codec<$ItemStackKey>;
        static ID: $ResourceLocation;
        static EMPTY: $ItemStackKey;
        constructor(arg0: $ItemStack_);
        get modId(): string;
        get tags(): $Stream<$TagKey<never>>;
        get typeId(): $ResourceLocation;
        get stackClass(): $Class<$ItemStack>;
        get sourceClass(): $Class<never>;
        get render(): $IStackRender;
        get vanillaMaxStackSize(): number;
        get customMaxStackSize(): number;
        get source(): $Object;
        get readOnlyStack(): $ItemStack;
        get renderStack(): $ItemStack;
        get emptyStack(): $ItemStack;
    }
    export class $EnergyStackKey extends $LongStackKey<$EnergyType> {
        getSource(): $EnergyType;
        deserialize(arg0: $RegistryFriendlyByteBuf): $EnergyStackKey;
        deserializeNBT(arg0: $CompoundTag_, arg1: $HolderLookup$Provider): $EnergyStackKey;
        fromSourceObject(arg0: $Object, arg1: $DataComponentPatch_): $EnergyStackKey;
        getEmptyStack(): $EnergyType;
        static TYPE_CODEC: $MapCodec<$EnergyStackKey>;
        static CODEC: $Codec<$EnergyStackKey>;
        static INSTANCE: $EnergyStackKey;
        static ID: $ResourceLocation;
        get source(): $EnergyType;
        get emptyStack(): $EnergyType;
    }
    export class $FluidStackKey implements $IStackKey<$FluidStack> {
        isEmpty(): boolean;
        serialize(arg0: $RegistryFriendlyByteBuf): void;
        getModId(): string;
        hasTag(arg0: $TagKey_<never>): boolean;
        getTags(): $Stream<$TagKey<never>>;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        deserializeNBT(arg0: $CompoundTag_, arg1: $HolderLookup$Provider): $FluidStackKey;
        codec(): $MapCodec<$FluidStackKey>;
        isSame(arg0: $IStackKey<never>): boolean;
        getTypeId(): $ResourceLocation;
        getStackClass(): $Class<$FluidStack>;
        copyStackWithCount(arg0: number): $FluidStack;
        getSourceClass(): $Class<never>;
        fromStackObject(arg0: $Object): $KeyAmount;
        getRender(): $IStackRender;
        getVanillaMaxStackSize(): number;
        isSameTypeSameComponents(arg0: $IStackKey<never>): boolean;
        getCustomMaxStackSize(): number;
        getSource(): $Object;
        deserialize(arg0: $RegistryFriendlyByteBuf): $IStackKey<$FluidStack>;
        getEmpty(): $IStackKey<$FluidStack>;
        copyStack(): $FluidStack;
        getReadOnlyStack(): $FluidStack;
        fromSourceObject(arg0: $Object, arg1: $DataComponentPatch_): $IStackKey<$FluidStack>;
        getRenderStack(): $FluidStack;
        getEmptyStack(): $FluidStack;
        static TYPE_CODEC: $MapCodec<$FluidStackKey>;
        static CODEC: $Codec<$FluidStackKey>;
        static ID: $ResourceLocation;
        static EMPTY: $FluidStackKey;
        constructor(arg0: $FluidStack_);
        get modId(): string;
        get tags(): $Stream<$TagKey<never>>;
        get typeId(): $ResourceLocation;
        get stackClass(): $Class<$FluidStack>;
        get sourceClass(): $Class<never>;
        get render(): $IStackRender;
        get vanillaMaxStackSize(): number;
        get customMaxStackSize(): number;
        get source(): $Object;
        get readOnlyStack(): $FluidStack;
        get renderStack(): $FluidStack;
        get emptyStack(): $FluidStack;
    }
}
