import { $Codec, $MapCodec } from "@package/com/mojang/serialization";
import { $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $EntityType_, $EquipmentSlot_, $PortalProcessor, $VariantHolder, $Pose_, $Entity, $EntityDimensions, $Entity$RemovalReason, $LivingEntity, $WalkAnimationState } from "@package/net/minecraft/world/entity";
import { $CallbackInfo, $CallbackInfoReturnable } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $ItemFrameAccessor } from "@package/com/simibubi/create/foundation/mixin/accessor";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $Map } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $InteractionHand, $InteractionHand_ } from "@package/net/minecraft/world";
import { $BootstrapContext } from "@package/net/minecraft/data/worldgen";
import { $SoundEvent } from "@package/net/minecraft/sounds";
import { $HolderLookup$Provider, $BlockPos, $Holder_, $Holder, $BlockPos_, $Direction_, $Rotations } from "@package/net/minecraft/core";
import { RegistryMarked, RegistryTypes } from "@special/types";
import { $RegistryFriendlyByteBuf } from "@package/net/minecraft/network";
import { $MapId } from "@package/net/minecraft/world/level/saveddata/maps";
import { $IDecorationEntity } from "@package/fi/dy/masa/tweakeroo/util";
import { $Record } from "@package/java/lang";
import { $AccessorMixinItemFrame } from "@package/noobanidus/mods/lootr/common/mixin/accessor";
import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $MobEffectInstance, $MobEffect } from "@package/net/minecraft/world/effect";
import { $IHangingEntityAccessor } from "@package/net/mehvahdjukaar/supplementaries/mixins";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $ResourceLocation_, $ResourceKey_, $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $ISupportTransmog } from "@package/io/redspace/ironslib/game/client";
import { $ByteBuf } from "@package/io/netty/buffer";
import { $ItemFrameEntityKJS } from "@package/dev/latvian/mods/kubejs/core";
import { $BaguAnimationController } from "@package/bagu_chan/bagus_lib/animation";
import { $Vec3_ } from "@package/net/minecraft/world/phys";
import { $DamageSource_ } from "@package/net/minecraft/world/damagesource";
import { $StreamCodec } from "@package/net/minecraft/network/codec";

declare module "@package/net/minecraft/world/entity/decoration" {
    export class $GlowItemFrame extends $ItemFrame {
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static NUM_ROTATIONS: number;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$ItemFrame>, arg1: $Level_);
        constructor(arg0: $Level_, arg1: $BlockPos_, arg2: $Direction_);
    }
    export class $ArmorStand extends $LivingEntity implements $ISupportTransmog {
        isSmall(): boolean;
        static createAttributes(): $AttributeSupplier$Builder;
        isMarker(): boolean;
        getDefaultDimensions(arg0: $Pose_): $EntityDimensions;
        irons_lib$getArmorBySlotRaw(arg0: $EquipmentSlot_): $ItemStack;
        handler$gne000$ftbchunks$onInteractAt(player: $Player, vec3: $Vec3_, interactionHand: $InteractionHand_, cir: $CallbackInfoReturnable<any>): void;
        setShowArms(arg0: boolean): void;
        isNoBasePlate(): boolean;
        setNoBasePlate(arg0: boolean): void;
        setHeadPose(arg0: $Rotations): void;
        setBodyPose(arg0: $Rotations): void;
        setRightArmPose(arg0: $Rotations): void;
        setLeftLegPose(arg0: $Rotations): void;
        setRightLegPose(arg0: $Rotations): void;
        setLeftArmPose(arg0: $Rotations): void;
        getLeftArmPose(): $Rotations;
        getHeadPose(): $Rotations;
        getBodyPose(): $Rotations;
        getLeftLegPose(): $Rotations;
        getRightArmPose(): $Rotations;
        getRightLegPose(): $Rotations;
        isShowArms(): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        static DEFAULT_BASE_GRAVITY: number;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        yHeadRot: number;
        noPhysics: boolean;
        yo: number;
        yBodyRotO: number;
        removalReason: $Entity$RemovalReason;
        zza: number;
        static CLIENT_FLAG_SMALL: number;
        swingingArm: $InteractionHand;
        static ID_TAG: string;
        static DATA_HEALTH_ID: $EntityDataAccessor<number>;
        lastHit: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        static DATA_RIGHT_LEG_POSE: $EntityDataAccessor<$Rotations>;
        xRotO: number;
        static WOBBLE_TIME: number;
        zo: number;
        walkDist: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        yya: number;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        hurtDuration: number;
        static DISABLE_PUTTING_OFFSET: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        dead: boolean;
        verticalCollision: boolean;
        verticalCollisionBelow: boolean;
        static DATA_LEFT_ARM_POSE: $EntityDataAccessor<$Rotations>;
        static DEFAULT_BABY_SCALE: number;
        eyeHeight: number;
        static ATTRIBUTES_FIELD: string;
        static DISABLE_TAKING_OFFSET: number;
        static DEFAULT_BB_HEIGHT: number;
        static DATA_RIGHT_ARM_POSE: $EntityDataAccessor<$Rotations>;
        xxa: number;
        static CLIENT_FLAG_NO_BASEPLATE: number;
        flyDist: number;
        static PASSENGERS_TAG: string;
        wasOnFire: boolean;
        attackAnim: number;
        zOld: number;
        static CLIENT_FLAG_MARKER: number;
        static DATA_CLIENT_FLAGS: $EntityDataAccessor<number>;
        timeOffs: number;
        wasTouchingWater: boolean;
        activeEffects: $Map<$Holder<$MobEffect>, $MobEffectInstance>;
        rotA: number;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        static ARMOR_SLOT_OFFSET: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        tickCount: number;
        static BOARDING_COOLDOWN: number;
        static DATA_HEAD_POSE: $EntityDataAccessor<$Rotations>;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        static DATA_LEFT_LEG_POSE: $EntityDataAccessor<$Rotations>;
        level: $Level;
        moveDist: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        xOld: number;
        wasInPowderSnow: boolean;
        hurtTime: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        deathTime: number;
        static CLIENT_FLAG_SHOW_ARMS: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        jumping: boolean;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        random: $RandomSource;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        removeArrowTime: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static DATA_BODY_POSE: $EntityDataAccessor<$Rotations>;
        yBodyRot: number;
        blocksBuilding: boolean;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        invulnerableDuration: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        effectsDirty: boolean;
        constructor(arg0: $EntityType_<$ArmorStand>, arg1: $Level_);
        constructor(arg0: $Level_, arg1: number, arg2: number, arg3: number);
        get small(): boolean;
        get marker(): boolean;
    }
    export class $LeashFenceKnotEntity extends $BlockAttachedEntity {
        static getOrCreateKnot(arg0: $Level_, arg1: $BlockPos_): $LeashFenceKnotEntity;
        playPlacementSound(): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        static OFFSET_Y: number;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$LeashFenceKnotEntity>, arg1: $Level_);
        constructor(arg0: $Level_, arg1: $BlockPos_);
    }
    export class $PaintingVariants {
        static register(arg0: $BootstrapContext<$PaintingVariant_>, arg1: $ResourceKey_<$PaintingVariant>, arg2: number, arg3: number): void;
        static bootstrap(arg0: $BootstrapContext<$PaintingVariant_>): void;
        static BACKYARD: $ResourceKey<$PaintingVariant>;
        static BOUQUET: $ResourceKey<$PaintingVariant>;
        static PRAIRIE_RIDE: $ResourceKey<$PaintingVariant>;
        static KEBAB: $ResourceKey<$PaintingVariant>;
        static BAROQUE: $ResourceKey<$PaintingVariant>;
        static OWLEMONS: $ResourceKey<$PaintingVariant>;
        static FIRE: $ResourceKey<$PaintingVariant>;
        static FINDING: $ResourceKey<$PaintingVariant>;
        static FERN: $ResourceKey<$PaintingVariant>;
        static TIDES: $ResourceKey<$PaintingVariant>;
        static WATER: $ResourceKey<$PaintingVariant>;
        static WIND: $ResourceKey<$PaintingVariant>;
        static BURNING_SKULL: $ResourceKey<$PaintingVariant>;
        static AZTEC: $ResourceKey<$PaintingVariant>;
        static LOWMIST: $ResourceKey<$PaintingVariant>;
        static FIGHTERS: $ResourceKey<$PaintingVariant>;
        static COURBET: $ResourceKey<$PaintingVariant>;
        static ENDBOSS: $ResourceKey<$PaintingVariant>;
        static SEA: $ResourceKey<$PaintingVariant>;
        static SKULL_AND_ROSES: $ResourceKey<$PaintingVariant>;
        static GRAHAM: $ResourceKey<$PaintingVariant>;
        static POOL: $ResourceKey<$PaintingVariant>;
        static PASSAGE: $ResourceKey<$PaintingVariant>;
        static VOID: $ResourceKey<$PaintingVariant>;
        static MEDITATIVE: $ResourceKey<$PaintingVariant>;
        static BOMB: $ResourceKey<$PaintingVariant>;
        static ORB: $ResourceKey<$PaintingVariant>;
        static AZTEC2: $ResourceKey<$PaintingVariant>;
        static WASTELAND: $ResourceKey<$PaintingVariant>;
        static COTAN: $ResourceKey<$PaintingVariant>;
        static PLANT: $ResourceKey<$PaintingVariant>;
        static EARTH: $ResourceKey<$PaintingVariant>;
        static DONKEY_KONG: $ResourceKey<$PaintingVariant>;
        static SKELETON: $ResourceKey<$PaintingVariant>;
        static POND: $ResourceKey<$PaintingVariant>;
        static WITHER: $ResourceKey<$PaintingVariant>;
        static ALBAN: $ResourceKey<$PaintingVariant>;
        static CAVEBIRD: $ResourceKey<$PaintingVariant>;
        static CREEBET: $ResourceKey<$PaintingVariant>;
        static PIGSCENE: $ResourceKey<$PaintingVariant>;
        static SUNSET: $ResourceKey<$PaintingVariant>;
        static STAGE: $ResourceKey<$PaintingVariant>;
        static SUNFLOWERS: $ResourceKey<$PaintingVariant>;
        static BUST: $ResourceKey<$PaintingVariant>;
        static CHANGING: $ResourceKey<$PaintingVariant>;
        static WANDERER: $ResourceKey<$PaintingVariant>;
        static UNPACKED: $ResourceKey<$PaintingVariant>;
        static HUMBLE: $ResourceKey<$PaintingVariant>;
        static POINTER: $ResourceKey<$PaintingVariant>;
        static MATCH: $ResourceKey<$PaintingVariant>;
        constructor();
    }
    export class $HangingEntity extends $BlockAttachedEntity implements $IHangingEntityAccessor {
        playPlacementSound(): void;
        invokeSetDirection(arg0: $Direction_): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
    }
    export class $PaintingVariant extends $Record {
        width(): number;
        area(): number;
        height(): number;
        assetId(): $ResourceLocation;
        static CODEC: $Codec<$Holder<$PaintingVariant>>;
        static DIRECT_CODEC: $Codec<$PaintingVariant>;
        static DIRECT_STREAM_CODEC: $StreamCodec<$ByteBuf, $PaintingVariant>;
        static STREAM_CODEC: $StreamCodec<$RegistryFriendlyByteBuf, $Holder<$PaintingVariant>>;
        constructor(arg0: number, arg1: number, arg2: $ResourceLocation_);
    }
    /**
     * Values that may be interpreted as {@link $PaintingVariant}.
     */
    export type $PaintingVariant_ = RegistryTypes.PaintingVariant | { width?: number, height?: number, assetId?: $ResourceLocation_,  } | [width?: number, height?: number, assetId?: $ResourceLocation_, ];
    export class $ItemFrame extends $HangingEntity implements $AccessorMixinItemFrame, $ItemFrameEntityKJS, $ItemFrameAccessor {
        getItem(): $ItemStack;
        handler$gni000$ftbchunks$onHurt(damageSource: $DamageSource_, f: number, cir: $CallbackInfoReturnable<any>): void;
        static getDataItem$lootr_$md$70d283$0(): $EntityDataAccessor<any>;
        setItem(arg0: $ItemStack_, arg1: boolean): void;
        setItem(arg0: $ItemStack_): void;
        getRotation(): number;
        setRotation(arg0: number): void;
        getAnalogOutput(): number;
        getPlaceSound(): $SoundEvent;
        getBreakSound(): $SoundEvent;
        getFramedMapId(arg0: $ItemStack_): $MapId;
        hasFramedMap(): boolean;
        getAddItemSound(): $SoundEvent;
        getRotateItemSound(): $SoundEvent;
        getRemoveItemSound(): $SoundEvent;
        create$getFrameItemStack(): $ItemStack;
        lootr$onItemChanged(arg0: $ItemStack_): void;
        lootr$isFixed(): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static NUM_ROTATIONS: number;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $EntityType_<$ItemFrame>, arg1: $Level_, arg2: $BlockPos_, arg3: $Direction_);
        constructor(arg0: $Level_, arg1: $BlockPos_, arg2: $Direction_);
        constructor(arg0: $EntityType_<$ItemFrame>, arg1: $Level_);
        static get dataItem$lootr_$md$70d283$0(): $EntityDataAccessor<any>;
        get analogOutput(): number;
        get placeSound(): $SoundEvent;
        get breakSound(): $SoundEvent;
        get addItemSound(): $SoundEvent;
        get rotateItemSound(): $SoundEvent;
        get removeItemSound(): $SoundEvent;
    }
    export class $Painting extends $HangingEntity implements $VariantHolder<$Holder<$PaintingVariant>> {
        static create(arg0: $Level_, arg1: $BlockPos_, arg2: $Direction_): ($Painting) | undefined;
        setVariant(arg0: $Holder_<$PaintingVariant>): void;
        getVariant(): $Holder<$PaintingVariant>;
        serializeNBT(arg0: $HolderLookup$Provider): $Holder<$PaintingVariant>;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static VARIANT_MAP_CODEC: $MapCodec<$Holder<$PaintingVariant>>;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        static VARIANT_CODEC: $Codec<$Holder<$PaintingVariant>>;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        static DEPTH: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(arg0: $Level_, arg1: $BlockPos_, arg2: $Direction_, arg3: $Holder_<$PaintingVariant>);
        constructor(arg0: $EntityType_<$Painting>, arg1: $Level_);
    }
    export interface $PaintingVariant extends RegistryMarked<RegistryTypes.PaintingVariantTag, RegistryTypes.PaintingVariant> {}
    export class $BlockAttachedEntity extends $Entity implements $IDecorationEntity {
        survives(): boolean;
        getPos(): $BlockPos;
        handler$ign00c$maid_storage_manager$tick(arg0: $CallbackInfo): void;
        tweakeroo$getAttached(): $BlockPos;
        addAdditionalSaveData(arg0: $CompoundTag_): void;
        readAdditionalSaveData(arg0: $CompoundTag_): void;
        dropItem(arg0: $Entity): void;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        hasImpulse: boolean;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        level: $Level;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        get pos(): $BlockPos;
    }
}
