import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $GoalSelector } from "@package/net/minecraft/world/entity/ai/goal";
import { $DyeColor_, $ItemStack_, $ItemStack, $DyeColor } from "@package/net/minecraft/world/item";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $PortalProcessor, $WalkAnimationState } from "@package/net/minecraft/world/entity";
import { $MobEffectInstance, $MobEffect } from "@package/net/minecraft/world/effect";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $List, $Map, $Set } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $AbstractGolem } from "@package/net/minecraft/world/entity/animal";
import { $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $PlayerModel } from "@package/net/minecraft/client/model";
import { $InteractionHand } from "@package/net/minecraft/world";
import { $HolderLookup$Provider, $BlockPos, $BlockPos_, $SectionPos, $Vec3i, $Holder } from "@package/net/minecraft/core";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $GameProfile } from "@package/com/mojang/authlib";
import { $ResourceKey } from "@package/net/minecraft/resources";
import { $Enum } from "@package/java/lang";
import { $BaguAnimationController } from "@package/bagu_chan/bagus_lib/animation";
import { $MountedToolbox } from "@package/com/railwayteam/railways/content/conductor/toolbox";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $Couple, $WorldAttached } from "@package/net/createmod/catnip/data";
export * as toolbox from "@package/com/railwayteam/railways/content/conductor/toolbox";

declare module "@package/com/railwayteam/railways/content/conductor" {
    export class $ConductorEntity extends $AbstractGolem {
        setColor(arg0: $DyeColor_): void;
        getColor(): $DyeColor;
        static isPlayerDisguised(arg0: $Player): boolean;
        isPossessedAndClient(): boolean;
        getOrCreateToolboxHolder(): $MountedToolbox;
        setChunkLoadingDistance(arg0: number): void;
        isCorrectEngineerCap(arg0: $ItemStack_): boolean;
        getSecondaryHeadStack(): $ItemStack;
        static hasRecentlyDismounted(arg0: $Player): boolean;
        isHoldingSchedulesClient(): boolean;
        getToolboxDisplayStack(): $ItemStack;
        updatePossessionInputs(): void;
        turnView(arg0: number, arg1: number): void;
        static createAttributes(): $AttributeSupplier$Builder;
        static colorFrom(arg0: number): $DyeColor;
        static canSpyInteract(arg0: $BlockState_): boolean;
        static defaultColor(): $DyeColor;
        getJob(): $ConductorEntity$Job;
        static spawn(arg0: $Level_, arg1: $BlockPos_, arg2: $ItemStack_): $ConductorEntity;
        doCheckFallDamage(arg0: number, arg1: boolean): void;
        stopViewing(arg0: $ServerPlayer): void;
        canReach(arg0: $Vec3i): boolean;
        static idFrom(arg0: $DyeColor_): number;
        getForwardSignalStrength(): number;
        startViewing(arg0: $ServerPlayer): boolean;
        getToolbox(): $MountedToolbox;
        setJob(arg0: $ConductorEntity$Job_): void;
        teleportToForce(arg0: number, arg1: number, arg2: number): void;
        addSchedule(arg0: $ItemStack_): void;
        isPossessed(): boolean;
        isHoldingSchedules(): boolean;
        hasSentChunks(): boolean;
        unequipToolbox(): $ItemStack;
        canUseBlock(arg0: $BlockState_): boolean;
        isInMinecart(): boolean;
        onSpyInteract(arg0: $BlockPos_): void;
        equipToolbox(arg0: $ItemStack_): void;
        setHasSentChunks(arg0: boolean): void;
        isCarryingToolbox(): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        static MAX_WEARING_ARMOR_CHANCE: number;
        static PRESERVE_ITEM_DROP_CHANCE_THRESHOLD: number;
        static DEFAULT_BASE_GRAVITY: number;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        static FREQUENCY_DATA: $Map<string, $Couple<$EntityDataAccessor<$ItemStack>>>;
        static RECENTLY_DISMOUNTED_PLAYERS: $List<$Player>;
        static MAX_PICKUP_LOOT_CHANCE: number;
        visualBaseEntity: $Player;
        lootTable: $ResourceKey<$LootTable>;
        yHeadRot: number;
        noPhysics: boolean;
        yo: number;
        yBodyRotO: number;
        removalReason: $Entity$RemovalReason;
        zza: number;
        goalSelector: $GoalSelector;
        swingingArm: $InteractionHand;
        static ID_TAG: string;
        static DATA_HEALTH_ID: $EntityDataAccessor<number>;
        persistenceRequired: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        yya: number;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        hurtDuration: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        xRotLast: number;
        yRotLast: number;
        dead: boolean;
        verticalCollision: boolean;
        verticalCollisionBelow: boolean;
        static DEFAULT_BABY_SCALE: number;
        eyeHeight: number;
        static ATTRIBUTES_FIELD: string;
        static UPDATE_GOAL_SELECTOR_EVERY_N_TICKS: number;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        yLast: number;
        flyDist: number;
        static PASSENGERS_TAG: string;
        wasOnFire: boolean;
        attackAnim: number;
        zOld: number;
        firstGoodY: number;
        timeOffs: number;
        firstGoodZ: number;
        oldSectionPos: $SectionPos;
        firstGoodX: number;
        wasTouchingWater: boolean;
        activeEffects: $Map<$Holder<$MobEffect>, $MobEffectInstance>;
        rotA: number;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        visualBaseModel: $PlayerModel<never>;
        static HOLDING_SCHEDULES: $EntityDataAccessor<boolean>;
        static DEFAULT_EQUIPMENT_DROP_CHANCE: number;
        static ARMOR_SLOT_OFFSET: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        xLast: number;
        tickCount: number;
        static COLOR: $EntityDataAccessor<number>;
        static MAX_ENCHANTED_ARMOR_CHANCE: number;
        static MAX_ENCHANTED_WEAPON_CHANCE: number;
        static JOB: $EntityDataAccessor<number>;
        receivedMovePacketCount: number;
        static BOARDING_COOLDOWN: number;
        static PRESERVE_ITEM_DROP_CHANCE: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        level: $Level;
        ambientSoundTime: number;
        static BLOCK: $EntityDataAccessor<$BlockPos>;
        moveDist: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        targetSelector: $GoalSelector;
        bob: number;
        xOld: number;
        wasInPowderSnow: boolean;
        hurtTime: number;
        ventCooldown: number;
        xpReward: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        static FAKE_PLAYER_PROFILE: $GameProfile;
        deathTime: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        jumping: boolean;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static WITH_TOOLBOXES: $WorldAttached<$Set<$ConductorEntity>>;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        random: $RandomSource;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        knownMovePacketCount: number;
        removeArrowTime: number;
        walkDistO: number;
        lastGoodX: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        lastGoodY: number;
        lastGoodZ: number;
        zLast: number;
        yBodyRot: number;
        blocksBuilding: boolean;
        oBob: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        invulnerableDuration: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        effectsDirty: boolean;
        constructor(arg0: $EntityType_<$AbstractGolem>, arg1: $Level_);
        get possessedAndClient(): boolean;
        get orCreateToolboxHolder(): $MountedToolbox;
        set chunkLoadingDistance(value: number);
        get secondaryHeadStack(): $ItemStack;
        get holdingSchedulesClient(): boolean;
        get toolboxDisplayStack(): $ItemStack;
        get forwardSignalStrength(): number;
        get toolbox(): $MountedToolbox;
        get possessed(): boolean;
        get holdingSchedules(): boolean;
        get inMinecart(): boolean;
        get carryingToolbox(): boolean;
    }
    export class $ServerPlayerPossessionAccess {
    }
    export interface $ServerPlayerPossessionAccess {
        railways$getPossessedConductor(): $ConductorEntity;
        railways$setPossessedConductor(arg0: $ConductorEntity): void;
    }
    export class $ConductorEntity$Job extends $Enum<$ConductorEntity$Job> {
        static values(): $ConductorEntity$Job[];
        static valueOf(arg0: string): $ConductorEntity$Job;
        static TOOLBOX_CARRIER: $ConductorEntity$Job;
        static REDSTONE_OPERATOR: $ConductorEntity$Job;
        static SPY: $ConductorEntity$Job;
        static REMOTE_CONTROL: $ConductorEntity$Job;
        static DEFAULT: $ConductorEntity$Job;
    }
    /**
     * Values that may be interpreted as {@link $ConductorEntity$Job}.
     */
    export type $ConductorEntity$Job_ = "redstone_operator" | "toolbox_carrier" | "remote_control" | "spy";
}
