import { $GoalSelector } from "@package/net/minecraft/world/entity/ai/goal";
import { $MoveControl } from "@package/net/minecraft/world/entity/ai/control";
import { $YoukaiCombatManager, $YoukaiTargetContainer, $YoukaiCardHolder } from "@package/dev/xkmc/youkaishomecoming/content/entity/behavior/combat";
import { $CompoundTag } from "@package/net/minecraft/nbt";
import { $EntityType_, $PortalProcessor, $Entity, $EntityDimensions, $Entity$RemovalReason, $LivingEntity, $WalkAnimationState } from "@package/net/minecraft/world/entity";
import { $IDanmakuEntity, $IYoukaiEntity } from "@package/dev/xkmc/danmakuapi/api";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $Map } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $InteractionHand } from "@package/net/minecraft/world";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $HolderLookup$Provider, $BlockPos, $Holder } from "@package/net/minecraft/core";
import { $SimplifiedProjectile } from "@package/dev/xkmc/fastprojectileapi/entity";
import { $PathNavigation } from "@package/net/minecraft/world/entity/ai/navigation";
import { $DamageClampEntity } from "@package/dev/xkmc/youkaishomecoming/content/entity/foundation";
import { $Enum, $Record, $Class } from "@package/java/lang";
import { $LootTable } from "@package/net/minecraft/world/level/storage/loot";
import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $DyeColor_ } from "@package/net/minecraft/world/item";
import { $SpellCardWrapper } from "@package/dev/xkmc/danmakuapi/content/spell/spellcard";
import { $SpellCircleHolder } from "@package/dev/xkmc/fastprojectileapi/spellcircle";
import { $MobEffectInstance, $MobEffect } from "@package/net/minecraft/world/effect";
import { $YoukaiNavigationControl } from "@package/dev/xkmc/youkaishomecoming/content/entity/behavior/move";
import { $Player } from "@package/net/minecraft/world/entity/player";
import { $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $CharDataHolder, $ReputationState } from "@package/dev/xkmc/youkaishomecoming/content/attachment/character";
import { $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $BaguAnimationController } from "@package/bagu_chan/bagus_lib/animation";
import { $Vec3_ } from "@package/net/minecraft/world/phys";
import { $DamageSource_ } from "@package/net/minecraft/world/damagesource";

declare module "@package/dev/xkmc/youkaishomecoming/content/entity/youkai" {
    export class $YoukaiFeatureSet$Builder {
        limit(arg0: number, arg1: number): $YoukaiFeatureSet$Builder;
        build(): $YoukaiFeatureSet;
        noPlayerTime(arg0: number): $YoukaiFeatureSet$Builder;
        damageCoolDown(): $YoukaiFeatureSet$Builder;
        damageFilter(): $YoukaiFeatureSet$Builder;
        markBoss(): $YoukaiFeatureSet$Builder;
        trueDamageOnImmune(): $YoukaiFeatureSet$Builder;
        constructor();
    }
    export class $YoukaiFlags extends $Enum<$YoukaiFlags> {
        static values(): $YoukaiFlags[];
        static valueOf(arg0: string): $YoukaiFlags;
        static HAIRBAND_TRADED: $YoukaiFlags;
        static FED: $YoukaiFlags;
        static FAINTED: $YoukaiFlags;
        static NONE: $YoukaiFlags;
        static CHARGING: $YoukaiFlags;
        static POWERED: $YoukaiFlags;
    }
    /**
     * Values that may be interpreted as {@link $YoukaiFlags}.
     */
    export type $YoukaiFlags_ = "charging" | "fainted" | "powered" | "none" | "fed" | "hairband_traded";
    export class $YoukaiEntity extends $DamageClampEntity implements $SpellCircleHolder, $IYoukaiEntity {
        getModule<T>(arg0: $Class<T>): (T) | undefined;
        getData(arg0: $Entity): ($CharDataHolder) | undefined;
        getFlag(arg0: $YoukaiFlags_): boolean;
        setFlag(arg0: $YoukaiFlags_, arg1: boolean): void;
        static createAttributes(): $AttributeSupplier$Builder;
        getReputation(arg0: $LivingEntity): $ReputationState;
        mayInteract(arg0: $Player): boolean;
        setTalkTo(arg0: $ServerPlayer, arg1: number): void;
        shoot(arg0: number, arg1: number, arg2: $Vec3_, arg3: $DyeColor_): void;
        isHostileTo(arg0: $LivingEntity): boolean;
        getCircleSize(arg0: number): number;
        getSpellCircle(): $ResourceLocation;
        onDanmakuHit(arg0: $LivingEntity, arg1: $IDanmakuEntity): void;
        onDanmakuImmune(arg0: $LivingEntity, arg1: $IDanmakuEntity, arg2: $DamageSource_): void;
        setControl(arg0: $MoveControl, arg1: $PathNavigation): void;
        shouldHurt(arg0: $LivingEntity): boolean;
        eraseAllDanmaku(arg0: $Player): void;
        refreshIdle(): void;
        initSpellCard(): void;
        danmakuHitTarget(arg0: $IDanmakuEntity, arg1: $DamageSource_, arg2: $LivingEntity): void;
        trackDanmaku(arg0: $SimplifiedProjectile): void;
        resetTarget(arg0: $Player): void;
        shouldShowSpellCircle(): boolean;
        wouldInitiateAttack(arg0: $LivingEntity): boolean;
        serializeNBT(arg0: $HolderLookup$Provider): $CompoundTag;
        static MAX_WEARING_ARMOR_CHANCE: number;
        static PRESERVE_ITEM_DROP_CHANCE_THRESHOLD: number;
        static DEFAULT_BASE_GRAVITY: number;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        static MAX_PICKUP_LOOT_CHANCE: number;
        lootTable: $ResourceKey<$LootTable>;
        yHeadRot: number;
        noPhysics: boolean;
        yo: number;
        yBodyRotO: number;
        removalReason: $Entity$RemovalReason;
        zza: number;
        goalSelector: $GoalSelector;
        swingingArm: $InteractionHand;
        static ID_TAG: string;
        static DATA_HEALTH_ID: $EntityDataAccessor<number>;
        spellCard: $SpellCardWrapper;
        persistenceRequired: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        navCtrl: $YoukaiNavigationControl;
        combatManager: $YoukaiCombatManager;
        yya: number;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        hurtDuration: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        dead: boolean;
        verticalCollision: boolean;
        targets: $YoukaiTargetContainer;
        verticalCollisionBelow: boolean;
        static DEFAULT_BABY_SCALE: number;
        eyeHeight: number;
        static ATTRIBUTES_FIELD: string;
        static UPDATE_GOAL_SELECTOR_EVERY_N_TICKS: number;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        cardHolder: $YoukaiCardHolder;
        flyDist: number;
        static PASSENGERS_TAG: string;
        wasOnFire: boolean;
        attackAnim: number;
        zOld: number;
        timeOffs: number;
        wasTouchingWater: boolean;
        activeEffects: $Map<$Holder<$MobEffect>, $MobEffectInstance>;
        rotA: number;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        static DEFAULT_EQUIPMENT_DROP_CHANCE: number;
        static ARMOR_SLOT_OFFSET: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        tickCount: number;
        static MAX_ENCHANTED_ARMOR_CHANCE: number;
        static MAX_ENCHANTED_WEAPON_CHANCE: number;
        static BOARDING_COOLDOWN: number;
        static PRESERVE_ITEM_DROP_CHANCE: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        level: $Level;
        ambientSoundTime: number;
        moveDist: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        targetSelector: $GoalSelector;
        xOld: number;
        wasInPowderSnow: boolean;
        hurtTime: number;
        xpReward: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        deathTime: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        jumping: boolean;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        random: $RandomSource;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        removeArrowTime: number;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        yBodyRot: number;
        blocksBuilding: boolean;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        invulnerableDuration: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        effectsDirty: boolean;
        constructor(arg0: $EntityType_<$YoukaiEntity>, arg1: $Level_, arg2: number);
        constructor(arg0: $EntityType_<$YoukaiEntity>, arg1: $Level_);
        get spellCircle(): $ResourceLocation;
    }
    export class $YoukaiFeatureSet extends $Record {
        static builder(): $YoukaiFeatureSet$Builder;
        maxSpeed(): number;
        hasBossBar(): boolean;
        limiter(): number;
        nonDanmakuProtection(): number;
        noTargetHealing(): boolean;
        effectImmune(): boolean;
        damageCoolDown(): boolean;
        damageFilter(): boolean;
        noPlayerDiscardTime(): number;
        trueDamageOnImmune(): boolean;
        static BOSS: $YoukaiFeatureSet;
        static MAIDEN: $YoukaiFeatureSet;
        static SAGE: $YoukaiFeatureSet;
        static NONE: $YoukaiFeatureSet;
        static FULL: $YoukaiFeatureSet;
        constructor(effectImmune: boolean, damageFilter: boolean, damageCoolDown: boolean, noTargetHealing: boolean, trueDamageOnImmune: boolean, hasBossBar: boolean, limiter: number, nonDanmakuProtection: number, noPlayerDiscardTime: number, maxSpeed: number);
    }
    /**
     * Values that may be interpreted as {@link $YoukaiFeatureSet}.
     */
    export type $YoukaiFeatureSet_ = { maxSpeed?: number, effectImmune?: boolean, limiter?: number, nonDanmakuProtection?: number, trueDamageOnImmune?: boolean, noPlayerDiscardTime?: number, damageCoolDown?: boolean, hasBossBar?: boolean, damageFilter?: boolean, noTargetHealing?: boolean,  } | [maxSpeed?: number, effectImmune?: boolean, limiter?: number, nonDanmakuProtection?: number, trueDamageOnImmune?: boolean, noPlayerDiscardTime?: number, damageCoolDown?: boolean, hasBossBar?: boolean, damageFilter?: boolean, noTargetHealing?: boolean, ];
}
