import { $PrintWriter } from "@package/java/io";
import { $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $DimensionSpecialEffects } from "@package/net/minecraft/client/renderer";
import { $RegionDetection } from "@package/xaero/map/file";
import { $LeveledRegion, $LayeredRegionManager } from "@package/xaero/map/region";
import { $DimensionHighlighterHandler, $HighlighterRegistry } from "@package/xaero/map/highlight";
import { $CallbackInfo } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $Minecraft } from "@package/net/minecraft/client";
import { $ArrayList, $List, $List_, $Hashtable } from "@package/java/util";
import { $ClientLevel } from "@package/net/minecraft/client/multiplayer";
import { $Registry } from "@package/net/minecraft/core";
import { $Path } from "@package/java/nio/file";
import { $MapFullReloader, $MapProcessor } from "@package/xaero/map";
import { $ResourceKey_, $ResourceKey, $ResourceLocation } from "@package/net/minecraft/resources";
import { $Object, $Iterable } from "@package/java/lang";
import { $MapWorldDuck } from "@package/dev/satherov/ftbxaerocompat/duck";
import { $DimensionType, $DimensionType_ } from "@package/net/minecraft/world/level/dimension";

declare module "@package/xaero/map/world" {
    export class $MapConnectionManager {
        isEmpty(): boolean;
        save(arg0: $PrintWriter): void;
        isConnected(arg0: $MapConnectionNode, arg1: $MapConnectionNode): boolean;
        removeConnection(arg0: $MapConnectionNode, arg1: $MapConnectionNode): void;
        addConnection(arg0: $MapConnectionNode, arg1: $MapConnectionNode): void;
        renameDimension(arg0: string, arg1: string): void;
        constructor();
        get empty(): boolean;
    }
    export class $MapWorld implements $MapWorldDuck {
        load(): void;
        getDimensions(arg0: $List_<$MapDimension>): void;
        getDimension(arg0: $ResourceKey_<$Level>): $MapDimension;
        saveConfig(): void;
        getCurrentDimension(): $MapDimension;
        clearAllCachedHighlightHashes(): void;
        switchToFutureMultiworldTypeUnsynced(): void;
        getEffectiveDimensionTeleportCommandFormat(): string;
        getEffectivePlayerTeleportCommandFormat(): string;
        getCurrentDimensionId(): $ResourceKey<$Level>;
        isIgnoreHeightmaps(): boolean;
        isCacheOnlyMode(): boolean;
        getMapProcessor(): $MapProcessor;
        toggleDimension(arg0: boolean): void;
        isMultiplayer(): boolean;
        handler$hlh000$ftbxaerocompat$createDimensionUnsynced(ci: $CallbackInfo): void;
        static convertWorldFolderToRootId(arg0: number, arg1: string): string;
        setIgnoreHeightmaps(arg0: boolean): void;
        isUsingUnknownDimensionType(): boolean;
        isIgnoreServerLevelId(): boolean;
        createDimensionUnsynced(arg0: $ResourceKey_<$Level>): $MapDimension;
        getFutureDimension(): $MapDimension;
        unconfirmMultiworldTypeUnsynced(): void;
        isCurrentMultiworldTypeConfirmed(): boolean;
        isFutureMultiworldTypeConfirmed(arg0: $MapDimension): boolean;
        setUseDefaultPlayerTeleport(arg0: boolean): void;
        getPlayerTeleportCommandFormat(): string;
        setPlayerTeleportCommandFormat(arg0: string): void;
        getEffectiveTeleportCommandFormat(): string;
        getDimensionTeleportCommandFormat(): string;
        setDimensionTeleportCommandFormat(arg0: string): void;
        isUsingDefaultPlayerTeleport(): boolean;
        getMainId(): string;
        getFutureDimensionId(): $ResourceKey<$Level>;
        getCustomDimensionId(): $ResourceKey<$Level>;
        getCurrentMultiworld(): string;
        isUsingCustomDimension(): boolean;
        getDimensionsList(): $List<$MapDimension>;
        getPotentialDimId(): $ResourceKey<$Level>;
        getPlayerMapKey(): $MapConnectionNode;
        getMapConnections(): $MapConnectionManager;
        setFutureDimensionId(arg0: $ResourceKey_<$Level>): void;
        switchToFutureUnsynced(): void;
        onWorldChangeUnsynced(arg0: $ClientLevel): void;
        getOldUnfixedMainId(): string;
        setCustomDimensionId(arg0: $ResourceKey_<$Level>): void;
        getCurrentMultiworldType(): number;
        getFutureMultiworldType(arg0: $MapDimension): number;
        getTeleportCommandFormat(): string;
        setUseDefaultMapTeleport(arg0: boolean): void;
        setTeleportCommandFormat(arg0: string): void;
        isUsingDefaultMapTeleport(): boolean;
        ftbxaerocompat$isLoaded(): boolean;
        toggleMultiworldTypeUnsynced(): void;
        confirmMultiworldTypeUnsynced(): void;
        getFutureMultiworldUnsynced(): string;
        constructor(arg0: string, arg1: string, arg2: $MapProcessor);
        get currentDimension(): $MapDimension;
        get effectiveDimensionTeleportCommandFormat(): string;
        get effectivePlayerTeleportCommandFormat(): string;
        get currentDimensionId(): $ResourceKey<$Level>;
        get cacheOnlyMode(): boolean;
        get mapProcessor(): $MapProcessor;
        get multiplayer(): boolean;
        get usingUnknownDimensionType(): boolean;
        get ignoreServerLevelId(): boolean;
        get futureDimension(): $MapDimension;
        get currentMultiworldTypeConfirmed(): boolean;
        set useDefaultPlayerTeleport(value: boolean);
        get effectiveTeleportCommandFormat(): string;
        get usingDefaultPlayerTeleport(): boolean;
        get mainId(): string;
        get currentMultiworld(): string;
        get usingCustomDimension(): boolean;
        get dimensionsList(): $List<$MapDimension>;
        get potentialDimId(): $ResourceKey<$Level>;
        get playerMapKey(): $MapConnectionNode;
        get mapConnections(): $MapConnectionManager;
        get oldUnfixedMainId(): string;
        get currentMultiworldType(): number;
        set useDefaultMapTeleport(value: boolean);
        get usingDefaultMapTeleport(): boolean;
        get futureMultiworldUnsynced(): string;
    }
    export class $MapConnectionNode {
        static fromString(arg0: string): $MapConnectionNode;
        getNamedString(arg0: $MapWorld): string;
        getDimId(): $ResourceKey<$Level>;
        getMw(): string;
        constructor(arg0: $ResourceKey_<$Level>, arg1: string);
        get dimId(): $ResourceKey<$Level>;
        get mw(): string;
    }
    export class $MapDimension {
        clear(): void;
        getSkyDarken(arg0: number, arg1: $ClientLevel, arg2: $Registry<$DimensionType_>): number;
        getLayeredMapRegions(): $LayeredRegionManager;
        getMapWorld(): $MapWorld;
        isCacheOnlyMode(arg0: $Registry<$DimensionType_>): boolean;
        isUsingWorldSave(): boolean;
        getDimensionTypeId(): $ResourceLocation;
        getFullReloader(): $MapFullReloader;
        calculateDimScale(arg0: $Registry<$DimensionType_>): number;
        startFullMapReload(arg0: number, arg1: boolean, arg2: $MapProcessor): void;
        clearFullMapReload(): void;
        calculateDimDiv(arg0: $Registry<$DimensionType_>, arg1: $DimensionType_): number;
        getDimensionEffects(arg0: $Registry<$DimensionType_>): $DimensionSpecialEffects;
        getDimensionType(arg0: $Registry<$DimensionType_>): $DimensionType;
        static getDimensionType(arg0: $MapDimension, arg1: $ResourceKey_<$Level>, arg2: $Registry<$DimensionType_>): $DimensionType;
        isUsingUnknownDimensionType(arg0: $Registry<$DimensionType_>): boolean;
        getWorldSaveDetectedRegions(): $Iterable<$Hashtable<number, $RegionDetection>>;
        getCaveModeType(): number;
        getMultiworldName(arg0: string): string;
        getMultiworldIdsCopy(): $List<string>;
        deleteMultiworldMapDataUnsynced(arg0: string): void;
        getDimId(): $ResourceKey<$Level>;
        getShadowR(): number;
        getShadowG(): number;
        getShadowB(): number;
        getHighlightHandler(): $DimensionHighlighterHandler;
        getCurrentMultiworld(): string;
        getMainFolderPath(): $Path;
        saveConfigUnsynced(): void;
        getOldFolderPath(): $Path;
        setMultiworldName(arg0: string, arg1: string): void;
        deleteMultiworldId(arg0: string): void;
        isAutoSelected(): boolean;
        toggleCaveModeType(arg0: boolean): void;
        preDetection(): void;
        onCreationUnsynced(): void;
        getPlayerMapKey(): $MapConnectionNode;
        getFutureCustomSelectedMultiworld(): string;
        isFutureUsingWorldSaveUnsynced(): boolean;
        getWorldSaveRegionDetection(arg0: number, arg1: number): $RegionDetection;
        getLinkedWorldSaveDetectedRegions(): $Iterable<$RegionDetection>;
        onClearCachedHighlightHashes(): void;
        hasConfirmedMultiworld(): boolean;
        setMultiworldUnsynced(arg0: string): void;
        confirmMultiworldUnsynced(): void;
        hasDoneRegionDetection(): boolean;
        switchToFutureUnsynced(): void;
        onWorldChangeUnsynced(arg0: $Level_): void;
        addMultiworldChecked(arg0: string): boolean;
        onClearCachedHighlightHash(arg0: number, arg1: number): void;
        getSelectedMapKeyUnsynced(): $MapConnectionNode;
        switchToFutureMultiworldWritableValueUnsynced(): void;
        addWorldSaveRegionDetection(arg0: $RegionDetection): void;
        resetCustomMultiworldUnsynced(): void;
        updateFutureAutomaticUnsynced(arg0: $Minecraft, arg1: $Object): void;
        isFutureMultiworldServerBased(): boolean;
        getFutureMultiworldUnsynced(): string;
        pickDefaultCustomMultiworldUnsynced(): void;
        futureMultiworldWritable: boolean;
        futureMultiworldServerBased: boolean;
        currentMultiworldWritable: boolean;
        regionsToCache: $ArrayList<$LeveledRegion<never>>;
        constructor(arg0: $MapWorld, arg1: $ResourceKey_<$Level>, arg2: $HighlighterRegistry);
        get layeredMapRegions(): $LayeredRegionManager;
        get mapWorld(): $MapWorld;
        get usingWorldSave(): boolean;
        get dimensionTypeId(): $ResourceLocation;
        get fullReloader(): $MapFullReloader;
        get worldSaveDetectedRegions(): $Iterable<$Hashtable<number, $RegionDetection>>;
        get caveModeType(): number;
        get multiworldIdsCopy(): $List<string>;
        get dimId(): $ResourceKey<$Level>;
        get shadowR(): number;
        get shadowG(): number;
        get shadowB(): number;
        get highlightHandler(): $DimensionHighlighterHandler;
        get currentMultiworld(): string;
        get mainFolderPath(): $Path;
        get oldFolderPath(): $Path;
        get autoSelected(): boolean;
        get playerMapKey(): $MapConnectionNode;
        get futureCustomSelectedMultiworld(): string;
        get futureUsingWorldSaveUnsynced(): boolean;
        get linkedWorldSaveDetectedRegions(): $Iterable<$RegionDetection>;
        set multiworldUnsynced(value: string);
        get selectedMapKeyUnsynced(): $MapConnectionNode;
        get futureMultiworldUnsynced(): string;
    }
}
