import { $Object, $Cloneable } from "@package/java/lang";

declare module "@package/me/shedaniel/math" {
    export class $Point implements $Cloneable {
        clone(): $Point;
        getLocation(): $Point;
        move(arg0: number, arg1: number): void;
        getY(): number;
        setLocation(arg0: number, arg1: number): void;
        getX(): number;
        translate(arg0: number, arg1: number): void;
        getFloatingLocation(): $FloatingPoint;
        x: number;
        y: number;
        constructor(arg0: number, arg1: number);
        constructor(arg0: number, arg1: number);
        constructor(arg0: $FloatingPoint);
        constructor(arg0: $Point);
        constructor();
        get floatingLocation(): $FloatingPoint;
    }
    export class $FloatingDimension implements $Cloneable {
        clone(): $Object;
        getSize(): $Dimension;
        setSize(arg0: $FloatingDimension): void;
        setSize(arg0: number, arg1: number): void;
        setSize(arg0: $Dimension): void;
        getWidth(): number;
        getHeight(): number;
        getFloatingSize(): $FloatingDimension;
        width: number;
        height: number;
        constructor(arg0: number, arg1: number);
        constructor(arg0: $FloatingDimension);
        constructor(arg0: $Dimension);
        constructor();
        get floatingSize(): $FloatingDimension;
    }
    export class $Rectangle implements $Cloneable {
        clone(): $Rectangle;
        isEmpty(): boolean;
        add(arg0: $FloatingPoint): void;
        add(arg0: $Point): void;
        add(arg0: number, arg1: number): void;
        add(arg0: $Rectangle): void;
        contains(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        contains(arg0: number, arg1: number): boolean;
        contains(arg0: $FloatingRectangle): boolean;
        contains(arg0: $Point): boolean;
        contains(arg0: $FloatingPoint): boolean;
        contains(arg0: number, arg1: number): boolean;
        contains(arg0: $Rectangle): boolean;
        getBounds(): $Rectangle;
        getLocation(): $Point;
        getSize(): $Dimension;
        grow(arg0: number, arg1: number): void;
        resize(arg0: number, arg1: number): void;
        move(arg0: number, arg1: number): void;
        setSize(arg0: $FloatingDimension): void;
        setSize(arg0: number, arg1: number): void;
        setSize(arg0: number, arg1: number): void;
        setSize(arg0: $Dimension): void;
        union(arg0: $Rectangle): $Rectangle;
        getWidth(): number;
        getY(): number;
        intersects(arg0: $Rectangle): boolean;
        setLocation(arg0: number, arg1: number): void;
        setLocation(arg0: number, arg1: number): void;
        setLocation(arg0: $FloatingPoint): void;
        setLocation(arg0: $Point): void;
        getHeight(): number;
        intersection(arg0: $Rectangle): $Rectangle;
        reshape(arg0: number, arg1: number, arg2: number, arg3: number): void;
        inside(arg0: number, arg1: number): boolean;
        getX(): number;
        setBounds(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setBounds(arg0: $Rectangle): void;
        setBounds(arg0: number, arg1: number, arg2: number, arg3: number): void;
        setBounds(arg0: $FloatingRectangle): void;
        translate(arg0: number, arg1: number): void;
        getCenterX(): number;
        getCenterY(): number;
        getMaxX(): number;
        getMinX(): number;
        getMinY(): number;
        getFloatingLocation(): $FloatingPoint;
        getMaxY(): number;
        getFloatingSize(): $FloatingDimension;
        getFloatingBounds(): $FloatingRectangle;
        x: number;
        width: number;
        y: number;
        height: number;
        constructor(arg0: $Dimension);
        constructor(arg0: $FloatingPoint);
        constructor(arg0: $Point);
        constructor(arg0: $FloatingPoint, arg1: $FloatingDimension);
        constructor(arg0: $FloatingDimension);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor(arg0: number, arg1: number);
        constructor(arg0: $FloatingRectangle);
        constructor(arg0: $Rectangle);
        constructor();
        constructor(arg0: $FloatingPoint, arg1: $Dimension);
        constructor(arg0: $Point, arg1: $FloatingDimension);
        constructor(arg0: $Point, arg1: $Dimension);
        get empty(): boolean;
        get centerX(): number;
        get centerY(): number;
        get maxX(): number;
        get minX(): number;
        get minY(): number;
        get floatingLocation(): $FloatingPoint;
        get maxY(): number;
        get floatingSize(): $FloatingDimension;
        get floatingBounds(): $FloatingRectangle;
    }
    export class $FloatingRectangle implements $Cloneable {
        clone(): $FloatingRectangle;
        isEmpty(): boolean;
        add(arg0: $FloatingPoint): void;
        add(arg0: $Point): void;
        add(arg0: number, arg1: number): void;
        add(arg0: $FloatingRectangle): void;
        contains(arg0: number, arg1: number, arg2: number, arg3: number): boolean;
        contains(arg0: number, arg1: number): boolean;
        contains(arg0: $Rectangle): boolean;
        contains(arg0: $Point): boolean;
        contains(arg0: $FloatingPoint): boolean;
        contains(arg0: number, arg1: number): boolean;
        contains(arg0: $FloatingRectangle): boolean;
        getBounds(): $Rectangle;
        getLocation(): $Point;
        getSize(): $Dimension;
        grow(arg0: number, arg1: number): void;
        resize(arg0: number, arg1: number): void;
        move(arg0: number, arg1: number): void;
        setSize(arg0: $FloatingDimension): void;
        setSize(arg0: $Dimension): void;
        setSize(arg0: number, arg1: number): void;
        union(arg0: $FloatingRectangle): $FloatingRectangle;
        getWidth(): number;
        getY(): number;
        intersects(arg0: $FloatingRectangle): boolean;
        setLocation(arg0: $FloatingPoint): void;
        setLocation(arg0: number, arg1: number): void;
        setLocation(arg0: $Point): void;
        getHeight(): number;
        intersection(arg0: $FloatingRectangle): $FloatingRectangle;
        reshape(arg0: number, arg1: number, arg2: number, arg3: number): void;
        inside(arg0: number, arg1: number): boolean;
        getX(): number;
        setBounds(arg0: $Rectangle): void;
        setBounds(arg0: $FloatingRectangle): void;
        setBounds(arg0: number, arg1: number, arg2: number, arg3: number): void;
        translate(arg0: number, arg1: number): void;
        getCenterX(): number;
        getCenterY(): number;
        getMaxX(): number;
        getMinX(): number;
        getMinY(): number;
        getFloatingLocation(): $FloatingPoint;
        getMaxY(): number;
        getFloatingBounds(): $FloatingRectangle;
        x: number;
        width: number;
        y: number;
        height: number;
        constructor(arg0: $FloatingPoint);
        constructor(arg0: $Point);
        constructor(arg0: $FloatingPoint, arg1: $FloatingDimension);
        constructor(arg0: $FloatingPoint, arg1: $Dimension);
        constructor(arg0: $Dimension);
        constructor(arg0: $FloatingDimension);
        constructor(arg0: number, arg1: number, arg2: number, arg3: number);
        constructor();
        constructor(arg0: $FloatingRectangle);
        constructor(arg0: $Rectangle);
        constructor(arg0: $Point, arg1: $FloatingDimension);
        constructor(arg0: $Point, arg1: $Dimension);
        constructor(arg0: number, arg1: number);
        get empty(): boolean;
        get centerX(): number;
        get centerY(): number;
        get maxX(): number;
        get minX(): number;
        get minY(): number;
        get floatingLocation(): $FloatingPoint;
        get maxY(): number;
        get floatingBounds(): $FloatingRectangle;
    }
    export class $Color {
        static ofOpaque(arg0: number): $Color;
        getColor(): number;
        brighter(arg0: number): $Color;
        darker(arg0: number): $Color;
        getRed(): number;
        getGreen(): number;
        getBlue(): number;
        static HSBtoRGB(arg0: number, arg1: number, arg2: number): number;
        getAlpha(): number;
        static ofTransparent(arg0: number): $Color;
        static ofRGB(arg0: number, arg1: number, arg2: number): $Color;
        static ofRGB(arg0: number, arg1: number, arg2: number): $Color;
        static ofRGBA(arg0: number, arg1: number, arg2: number, arg3: number): $Color;
        static ofRGBA(arg0: number, arg1: number, arg2: number, arg3: number): $Color;
        static ofHSB(arg0: number, arg1: number, arg2: number): $Color;
        get color(): number;
        get red(): number;
        get green(): number;
        get blue(): number;
        get alpha(): number;
    }
    export class $FloatingPoint implements $Cloneable {
        clone(): $FloatingPoint;
        getLocation(): $Point;
        move(arg0: number, arg1: number): void;
        getY(): number;
        setLocation(arg0: number, arg1: number): void;
        getX(): number;
        translate(arg0: number, arg1: number): void;
        getFloatingLocation(): $FloatingPoint;
        x: number;
        y: number;
        constructor(arg0: number, arg1: number);
        constructor(arg0: $FloatingPoint);
        constructor(arg0: $Point);
        constructor();
        get floatingLocation(): $FloatingPoint;
    }
    export class $Dimension implements $Cloneable {
        clone(): $Object;
        getSize(): $Dimension;
        setSize(arg0: $Dimension): void;
        setSize(arg0: number, arg1: number): void;
        setSize(arg0: $FloatingDimension): void;
        setSize(arg0: number, arg1: number): void;
        getWidth(): number;
        getHeight(): number;
        getFloatingSize(): $FloatingDimension;
        width: number;
        height: number;
        constructor(arg0: number, arg1: number);
        constructor(arg0: number, arg1: number);
        constructor(arg0: $FloatingDimension);
        constructor(arg0: $Dimension);
        constructor();
        get floatingSize(): $FloatingDimension;
    }
}
