import { $Codec } from "@package/com/mojang/serialization";
import { $Recipe, $Ingredient, $RecipeHolder_ } from "@package/net/minecraft/world/item/crafting";
import { $Either } from "@package/com/mojang/datafixers/util";
import { $ListTag_, $ListTag, $CompoundTag, $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $HumanoidArm, $EquipmentSlot_, $Pose_, $EntityDimensions, $Entity$RemovalReason, $LivingEntity, $WalkAnimationState, $HumanoidArm_, $Pose, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $CallbackInfo, $CallbackInfoReturnable } from "@package/org/spongepowered/asm/mixin/injection/callback";
import { $PlayerAccessor as $PlayerAccessor$1 } from "@package/io/redspace/ironslib/mixin";
import { $Mesh } from "@package/dev/tr7zw/skinlayers/api";
import { $LevelBlock } from "@package/dev/latvian/mods/kubejs/level";
import { $ItemPredicate_ } from "@package/dev/latvian/mods/kubejs/item";
import { $AnimationStack, $IAnimation } from "@package/dev/kosmx/playerAnim/api/layered";
import { $RandomSource, $SignatureValidator_, $Unit, $SignatureValidator, $OptionEnum } from "@package/net/minecraft/util";
import { $InteractionResult, $MenuProvider, $InteractionHand, $InteractionHand_, $Nameable, $Container } from "@package/net/minecraft/world";
import { $FakePlayer } from "@package/net/neoforged/neoforge/common/util";
import { $SoundEvent_, $SoundSource_ } from "@package/net/minecraft/sounds";
import { $IPlayerExtension } from "@package/net/neoforged/neoforge/common/extensions";
import { $NotificationToastData_, $AttachedData } from "@package/dev/latvian/mods/kubejs/util";
import { $BlockState_ } from "@package/net/minecraft/world/level/block/state";
import { $RegistryFriendlyByteBuf, $FriendlyByteBuf } from "@package/net/minecraft/network";
import { $GameProfile } from "@package/com/mojang/authlib";
import { $LocalIntRef } from "@package/com/llamalad7/mixinextras/sugar/ref";
import { $PlayerEnderChestContainer, $AbstractContainerMenu, $ClickAction_, $InventoryMenu } from "@package/net/minecraft/world/inventory";
import { $MerchantOffers } from "@package/net/minecraft/world/item/trading";
import { $Item_, $Item, $ItemCooldowns, $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $PlayerSettings } from "@package/dev/tr7zw/skinlayers/accessor";
import { $MutableComponent, $Component_, $ThrowingComponent, $Component } from "@package/net/minecraft/network/chat";
import { $IQuiverEntity } from "@package/net/mehvahdjukaar/supplementaries/common/entities";
import { $AnimationApplier } from "@package/dev/kosmx/playerAnim/impl/animation";
import { $MobEffectInstance, $MobEffect } from "@package/net/minecraft/world/effect";
import { $IMixinPlayerEntity } from "@package/fi/dy/masa/malilib/mixin/entity";
import { $PlayerData } from "@package/dev/tr7zw/notenoughanimations/access";
import { $FishingHook } from "@package/net/minecraft/world/entity/projectile";
import { $Instant, $Duration_, $Duration } from "@package/java/time";
import { $IAnimatedPlayer } from "@package/dev/kosmx/playerAnim/impl";
import { $CameraOperator, $CameraHolder } from "@package/io/github/mortuusars/exposure/world/entity";
import { $InventoryKJS, $PlayerKJS } from "@package/dev/latvian/mods/kubejs/core";
import { $AABB_, $Vec3 } from "@package/net/minecraft/world/phys";
import { $Stat_ } from "@package/net/minecraft/stats";
import { $AttributeSupplier$Builder } from "@package/net/minecraft/world/entity/ai/attributes";
import { $UUID_, $Set_, $Map, $OptionalInt, $List, $Collection_, $List_, $Collection, $BitSet, $Optional } from "@package/java/util";
import { $PlayerStatsJS, $KubeJSInventoryListener } from "@package/dev/latvian/mods/kubejs/player";
import { $WardenSpawnTracker } from "@package/net/minecraft/world/entity/monster/warden";
import { $AbstractHorse } from "@package/net/minecraft/world/entity/animal/horse";
import { $IPlayerMixin } from "@package/com/github/tartaricacid/touhoulittlemaid/api/mixin";
import { $DataHolder } from "@package/dev/tr7zw/notenoughanimations/versionless/animations";
import { $Supplier_, $Consumer_, $Predicate_ } from "@package/java/util/function";
import { $ServerPlayer } from "@package/net/minecraft/server/level";
import { $BlockPos, $GlobalPos, $BlockPos_, $GlobalPos_, $HolderLookup$Provider, $Holder, $Direction_, $NonNullList } from "@package/net/minecraft/core";
import { $Enum, $Record, $Object } from "@package/java/lang";
import { $IntList, $Int2IntMap } from "@package/it/unimi/dsi/fastutil/ints";
import { $GameType_, $BaseCommandBlock, $Level, $Level_ } from "@package/net/minecraft/world/level";
import { $TagKey_ } from "@package/net/minecraft/tags";
import { $Camera } from "@package/io/github/mortuusars/exposure/world/camera";
import { $PrivateKey, $PublicKey } from "@package/java/security";
import { $PlayerAccessor } from "@package/net/mehvahdjukaar/supplementaries/mixins";
import { $ItemEntity } from "@package/net/minecraft/world/entity/item";
import { $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $Stages } from "@package/dev/latvian/mods/kubejs/stages";
import { $StackedContentsRecipePickerAccessor } from "@package/umpaz/brewinandchewin/common/mixin";
import { $FoodProperties_, $FoodData } from "@package/net/minecraft/world/food";
import { $ResourceLocation, $ResourceLocation_ } from "@package/net/minecraft/resources";
import { $Scoreboard } from "@package/net/minecraft/world/scores";
import { $ISupportTransmog } from "@package/io/redspace/ironslib/game/client";
import { $BaguAnimationController } from "@package/bagu_chan/bagus_lib/animation";
import { $SignBlockEntity, $StructureBlockEntity, $JigsawBlockEntity, $CommandBlockEntity } from "@package/net/minecraft/world/level/block/entity";

declare module "@package/net/minecraft/world/entity/player" {
    export class $ProfileKeyPair extends $Record {
        publicKey(): $ProfilePublicKey;
        privateKey(): $PrivateKey;
        refreshedAfter(): $Instant;
        dueRefresh(): boolean;
        static CODEC: $Codec<$ProfileKeyPair>;
        constructor(arg0: $PrivateKey, arg1: $ProfilePublicKey_, arg2: $Instant);
    }
    /**
     * Values that may be interpreted as {@link $ProfileKeyPair}.
     */
    export type $ProfileKeyPair_ = { privateKey?: $PrivateKey, refreshedAfter?: $Instant, publicKey?: $ProfilePublicKey_,  } | [privateKey?: $PrivateKey, refreshedAfter?: $Instant, publicKey?: $ProfilePublicKey_, ];
    export class $ProfilePublicKey$Data extends $Record {
        write(arg0: $FriendlyByteBuf): void;
        key(): $PublicKey;
        hasExpired(arg0: $Duration_): boolean;
        hasExpired(): boolean;
        expiresAt(): $Instant;
        keySignature(): number[];
        static CODEC: $Codec<$ProfilePublicKey$Data>;
        constructor(arg0: $FriendlyByteBuf);
        constructor(arg0: $Instant, arg1: $PublicKey, arg2: number[]);
    }
    /**
     * Values that may be interpreted as {@link $ProfilePublicKey$Data}.
     */
    export type $ProfilePublicKey$Data_ = { expiresAt?: $Instant, key?: $PublicKey, keySignature?: number[],  } | [expiresAt?: $Instant, key?: $PublicKey, keySignature?: number[], ];
    export class $Abilities {
        loadSaveData(arg0: $CompoundTag_): void;
        getWalkingSpeed(): number;
        addSaveData(arg0: $CompoundTag_): void;
        setFlyingSpeed(arg0: number): void;
        getFlyingSpeed(): number;
        setWalkingSpeed(arg0: number): void;
        invulnerable: boolean;
        /**
         * @deprecated
         */
        mayfly: boolean;
        instabuild: boolean;
        mayBuild: boolean;
        flying: boolean;
        constructor();
    }
    export class $Inventory implements $Container, $Nameable {
        getName(): $Component;
        load(arg0: $ListTag_): void;
        isEmpty(): boolean;
        add(arg0: number, arg1: $ItemStack_): boolean;
        add(arg0: $ItemStack_): boolean;
        contains(arg0: $ItemStack_): boolean;
        contains(arg0: $Predicate_<$ItemStack>): boolean;
        contains(arg0: $TagKey_<$Item>): boolean;
        save(arg0: $ListTag_): $ListTag;
        replaceWith(arg0: $Inventory): void;
        tick(): void;
        getItem(arg0: number): $ItemStack;
        hasAnyMatching(arg0: $Predicate_<any>): boolean;
        getSelected(): $ItemStack;
        addResource(arg0: number, arg1: $ItemStack_): number;
        removeItem(arg0: $ItemStack_): void;
        removeItem(arg0: number, arg1: number): $ItemStack;
        pickSlot(arg0: number): void;
        swapPaint(arg0: number): void;
        getContainerSize(): number;
        getDestroySpeed(arg0: $BlockState_): number;
        removeItemNoUpdate(arg0: number): $ItemStack;
        handler$gpc000$moonlight$ml$fireDropEvent(arg0: $CallbackInfo, arg1: $List_<any>, arg2: number): void;
        setItem(arg0: number, arg1: $ItemStack_): void;
        dropAll(): void;
        stillValid(arg0: $Player): boolean;
        clearContent(): void;
        static isHotbarSlot(arg0: number): boolean;
        setPickedItem(arg0: $ItemStack_): void;
        findSlotMatchingUnusedItem(arg0: $ItemStack_): number;
        getSuitableHotbarSlot(): number;
        hasRemainingSpaceForItem(arg0: $ItemStack_, arg1: $ItemStack_): boolean;
        clearOrCountMatchingItems(arg0: $Predicate_<$ItemStack>, arg1: number, arg2: $Container): number;
        getSlotWithRemainingSpace(arg0: $ItemStack_): number;
        setChanged(): void;
        getArmor(arg0: number): $ItemStack;
        static getSelectionSize(): number;
        getFreeSlot(): number;
        getTimesChanged(): number;
        removeFromSelected(arg0: boolean): $ItemStack;
        findSlotMatchingItem(arg0: $ItemStack_): number;
        handler$gpc000$moonlight$ml$restoreNotDropped(arg0: $CallbackInfo, arg1: $List_<any>, arg2: number): void;
        fillStackedContents(arg0: $StackedContents): void;
        placeItemBackInInventory(arg0: $ItemStack_): void;
        placeItemBackInInventory(arg0: $ItemStack_, arg1: boolean): void;
        canPlaceItem(arg0: number, arg1: $ItemStack_): boolean;
        startOpen(arg0: $Player): void;
        stopOpen(arg0: $Player): void;
        hasAnyOf(arg0: $Set_<$Item_>): boolean;
        countItem(arg0: $Item_): number;
        getMaxStackSize(): number;
        getMaxStackSize(arg0: $ItemStack_): number;
        canTakeItem(arg0: $Container, arg1: number, arg2: $ItemStack_): boolean;
        getDisplayName(): $Component;
        hasCustomName(): boolean;
        getCustomName(): $Component;
        self(): $Container;
        isMutable(): boolean;
        getBlock(level: $Level_): $LevelBlock;
        clear(): void;
        asContainer(): $Container;
        getWidth(): number;
        getHeight(): number;
        setChanged(): void;
        setStackInSlot(slot: number, stack: $ItemStack_): void;
        getSlots(): number;
        getStackInSlot(slot: number): $ItemStack;
        insertItem(slot: number, stack: $ItemStack_, simulate: boolean): $ItemStack;
        extractItem(slot: number, amount: number, simulate: boolean): $ItemStack;
        getSlotLimit(slot: number): number;
        isItemValid(slot: number, stack: $ItemStack_): boolean;
        clear(match: $ItemPredicate_): void;
        find(): number;
        find(match: $ItemPredicate_): number;
        count(): number;
        count(match: $ItemPredicate_): number;
        isEmpty(): boolean;
        getAllItems(): $List<$ItemStack>;
        insertItem(stack: $ItemStack_, simulate: boolean): $ItemStack;
        countNonEmpty(): number;
        countNonEmpty(match: $ItemPredicate_): number;
        clientsort$setChanged(): void;
        static NOT_FOUND_INDEX: number;
        armor: $NonNullList<$ItemStack>;
        static INVENTORY_SIZE: number;
        static POP_TIME_DURATION: number;
        static SLOT_OFFHAND: number;
        static ALL_ARMOR_SLOTS: number[];
        items: $NonNullList<$ItemStack>;
        offhand: $NonNullList<$ItemStack>;
        selected: number;
        static HELMET_SLOT_ONLY: number[];
        player: $Player;
        constructor(arg0: $Player);
        get name(): $Component;
        get containerSize(): number;
        set pickedItem(value: $ItemStack_);
        get suitableHotbarSlot(): number;
        static get selectionSize(): number;
        get freeSlot(): number;
        get timesChanged(): number;
        get displayName(): $Component;
        get customName(): $Component;
        get mutable(): boolean;
        get width(): number;
        get height(): number;
        get slots(): number;
        get allItems(): $List<$ItemStack>;
    }
    export class $PlayerModelPart extends $Enum<$PlayerModelPart> {
        getName(): $Component;
        static values(): $PlayerModelPart[];
        static valueOf(arg0: string): $PlayerModelPart;
        getId(): string;
        getMask(): number;
        getBit(): number;
        static RIGHT_PANTS_LEG: $PlayerModelPart;
        static LEFT_PANTS_LEG: $PlayerModelPart;
        static JACKET: $PlayerModelPart;
        static RIGHT_SLEEVE: $PlayerModelPart;
        static HAT: $PlayerModelPart;
        static LEFT_SLEEVE: $PlayerModelPart;
        static CAPE: $PlayerModelPart;
        get id(): string;
        get mask(): number;
        get bit(): number;
    }
    /**
     * Values that may be interpreted as {@link $PlayerModelPart}.
     */
    export type $PlayerModelPart_ = "cape" | "jacket" | "left_sleeve" | "right_sleeve" | "left_pants_leg" | "right_pants_leg" | "hat";
    export class $StackedContents$RecipePicker implements $StackedContentsRecipePickerAccessor {
        tryPick(arg0: number, arg1: $IntList): boolean;
        tryPickAll(arg0: number, arg1: $IntList): number;
        brewinandchewin$setItemCount(arg0: number): void;
        brewinandchewin$invokeGetIndex(arg0: boolean, arg1: number, arg2: number): number;
        brewinandchewin$getItemCount(): number;
        brewinandchewin$getIngredients(): $List<$Ingredient>;
        brewinandchewin$getIngredientCount(): number;
        brewinandchewin$setIngredientCount(arg0: number): void;
        brewinandchewin$getData(): $BitSet;
        brewinandchewin$setData(arg0: $BitSet): void;
        brewinandchewin$setItems(arg0: number[]): void;
        brewinandchewin$getItems(): number[];
        brewinandchewin$invokeGetUniqueAvailableIngredientItems(): number[];
    }
    export class $ProfilePublicKey extends $Record {
        data(): $ProfilePublicKey$Data;
        createSignatureValidator(): $SignatureValidator;
        static createValidated(arg0: $SignatureValidator_, arg1: $UUID_, arg2: $ProfilePublicKey$Data_): $ProfilePublicKey;
        static EXPIRED_PROFILE_PUBLIC_KEY: $Component;
        static EXPIRY_GRACE_PERIOD: $Duration;
        static TRUSTED_CODEC: $Codec<$ProfilePublicKey>;
        constructor(arg0: $ProfilePublicKey$Data_);
    }
    /**
     * Values that may be interpreted as {@link $ProfilePublicKey}.
     */
    export type $ProfilePublicKey_ = { data?: $ProfilePublicKey$Data_,  } | [data?: $ProfilePublicKey$Data_, ];
    export class $Player$BedSleepingProblem extends $Enum<$Player$BedSleepingProblem> {
        static values(): $Player$BedSleepingProblem[];
        static valueOf(arg0: string): $Player$BedSleepingProblem;
        getMessage(): $Component;
        static OBSTRUCTED: $Player$BedSleepingProblem;
        static NOT_POSSIBLE_HERE: $Player$BedSleepingProblem;
        static NOT_POSSIBLE_NOW: $Player$BedSleepingProblem;
        static NOT_SAFE: $Player$BedSleepingProblem;
        static OTHER_PROBLEM: $Player$BedSleepingProblem;
        static TOO_FAR_AWAY: $Player$BedSleepingProblem;
        get message(): $Component;
    }
    /**
     * Values that may be interpreted as {@link $Player$BedSleepingProblem}.
     */
    export type $Player$BedSleepingProblem_ = "not_possible_here" | "not_possible_now" | "too_far_away" | "obstructed" | "other_problem" | "not_safe";
    export class $ChatVisiblity extends $Enum<$ChatVisiblity> implements $OptionEnum {
        static values(): $ChatVisiblity[];
        static valueOf(arg0: string): $ChatVisiblity;
        getKey(): string;
        getId(): number;
        static byId(arg0: number): $ChatVisiblity;
        getCaption(): $Component;
        static SYSTEM: $ChatVisiblity;
        static HIDDEN: $ChatVisiblity;
        static FULL: $ChatVisiblity;
        get key(): string;
        get id(): number;
        get caption(): $Component;
    }
    /**
     * Values that may be interpreted as {@link $ChatVisiblity}.
     */
    export type $ChatVisiblity_ = "full" | "system" | "hidden";
    export class $StackedContents {
        clear(): void;
        canCraft(arg0: $Recipe<never>, arg1: $IntList, arg2: number): boolean;
        canCraft(arg0: $Recipe<never>, arg1: $IntList): boolean;
        accountStack(arg0: $ItemStack_): void;
        accountStack(arg0: $ItemStack_, arg1: number): void;
        accountSimpleStack(arg0: $ItemStack_): void;
        static getStackingIndex(arg0: $ItemStack_): number;
        static fromStackingIndex(arg0: number): $ItemStack;
        getBiggestCraftableStack(arg0: $RecipeHolder_<never>, arg1: number, arg2: $IntList): number;
        getBiggestCraftableStack(arg0: $RecipeHolder_<never>, arg1: $IntList): number;
        contents: $Int2IntMap;
        constructor();
    }
    export class $ProfilePublicKey$ValidationException extends $ThrowingComponent {
        constructor(arg0: $Component_);
    }
    export class $Player extends $LivingEntity implements $IPlayerExtension, $IAnimatedPlayer, $CameraHolder, $CameraOperator, $PlayerAccessor, $IQuiverEntity, $IMixinPlayerEntity, $PlayerAccessor$1, $ISupportTransmog, $PlayerData, $IPlayerMixin, $PlayerSettings, $PlayerKJS {
        getData(holder: $DataHolder<any>, builder: $Supplier_<any>): $Object;
        drop(arg0: $ItemStack_, arg1: boolean, arg2: boolean): $ItemEntity;
        drop(arg0: $ItemStack_, arg1: boolean): $ItemEntity;
        getPrefixes(): $Collection<$MutableComponent>;
        resetAttackStrengthTicker(): void;
        displayClientMessage(arg0: $Component_, arg1: boolean): void;
        /**
         * Checks, whether the player is in Creative mode.
         */
        isCreative(): boolean;
        attack(arg0: $Entity): void;
        respawn(): void;
        isModelPartShown(arg0: $PlayerModelPart_): boolean;
        getSuffixes(): $Collection<$MutableComponent>;
        refreshDisplayName(): void;
        setForcedPose(arg0: $Pose_): void;
        getForcedPose(): $Pose;
        getAnimationStack(): $AnimationStack;
        getSideSword(): $ItemStack;
        isRotateBodyToHead(): boolean;
        getPoseOverwrite(): $Pose;
        setSideSword(sideSword: $ItemStack_): void;
        setPoseOverwrite(state: $Pose_): void;
        getLastHeldItems(): $ItemStack[];
        getLastRotations(): number[];
        getHeadMesh(): $Mesh;
        setLastRotations(lastRotations: number[]): void;
        setHeadMesh(headMesh: $Mesh): void;
        getTorsoMesh(): $Mesh;
        setTorsoMesh(torsoMesh: $Mesh): void;
        getRightArmMesh(): $Mesh;
        setLeftLegMesh(leftLegMesh: $Mesh): void;
        setRightLegMesh(rightLegMesh: $Mesh): void;
        getCurrentSkin(): $ResourceLocation;
        setThinArms(thin: boolean): void;
        getLeftArmMesh(): $Mesh;
        getRightLegMesh(): $Mesh;
        getLeftLegMesh(): $Mesh;
        setCurrentSkin(skin: $ResourceLocation_): void;
        hasThinArms(): boolean;
        setRightArmMesh(rightArmMesh: $Mesh): void;
        setLeftArmMesh(leftArmMesh: $Mesh): void;
        getEnchantmentSeed(): number;
        getFoodData(): $FoodData;
        mayUseItemAt(arg0: $BlockPos_, arg1: $Direction_, arg2: $ItemStack_): boolean;
        onUpdateAbilities(): void;
        addItem(arg0: $ItemStack_): boolean;
        getCooldowns(): $ItemCooldowns;
        mayBuild(): boolean;
        static createAttributes(): $AttributeSupplier$Builder;
        closeMenu(): void;
        stopSleepInBed(arg0: boolean, arg1: boolean): void;
        playNotifySound(arg0: $SoundEvent_, arg1: $SoundSource_, arg2: number, arg3: number): void;
        increaseScore(arg0: number): void;
        getDigSpeed(arg0: $BlockState_, arg1: $BlockPos_): number;
        /**
         * @deprecated
         */
        getDestroySpeed(arg0: $BlockState_): number;
        disableShield(): void;
        canHarmPlayer(arg0: $Player): boolean;
        openJigsawBlock(arg0: $JigsawBlockEntity): void;
        openHorseInventory(arg0: $AbstractHorse, arg1: $Container): void;
        sendMerchantOffers(arg0: number, arg1: $MerchantOffers, arg2: number, arg3: number, arg4: boolean, arg5: boolean): void;
        openItemGui(arg0: $ItemStack_, arg1: $InteractionHand_): void;
        openCommandBlock(arg0: $CommandBlockEntity): void;
        openTextEdit(arg0: $SignBlockEntity, arg1: boolean): void;
        openStructureBlock(arg0: $StructureBlockEntity): void;
        sweepAttack(): void;
        getSleepTimer(): number;
        hasContainerOpen(): boolean;
        startSleepInBed(arg0: $BlockPos_): $Either<$Player$BedSleepingProblem, $Unit>;
        awardRecipesByKey(arg0: $List_<$ResourceLocation_>): void;
        awardRecipes(arg0: $Collection_<$RecipeHolder_<never>>): number;
        startFallFlying(): void;
        stopFallFlying(): void;
        resetRecipes(arg0: $Collection_<$RecipeHolder_<never>>): number;
        static getDataPlayerModeCustomisation$irons_lib_$md$70d283$0(): $EntityDataAccessor<any>;
        handler$zei000$l2weaponry$hurtCurrentlyUsedShield_customShield(arg0: number, arg1: $CallbackInfo): void;
        awardStat(arg0: $Stat_<never>): void;
        awardStat(arg0: $Stat_<never>, arg1: number): void;
        awardStat(arg0: $ResourceLocation_, arg1: number): void;
        awardStat(arg0: $ResourceLocation_): void;
        getLuck(): number;
        setScore(arg0: number): void;
        getScore(): number;
        resetStat(arg0: $Stat_<never>): void;
        openMenu(arg0: $MenuProvider): $OptionalInt;
        interactOn(arg0: $Entity, arg1: $InteractionHand_): $InteractionResult;
        crit(arg0: $Entity): void;
        magicCrit(arg0: $Entity): void;
        getStages(): $Stages;
        getInventory(): $InventoryKJS;
        getData(): $AttachedData<any>;
        getAbilities(): $Abilities;
        isLocalPlayer(): boolean;
        getGameProfile(): $GameProfile;
        isReducedDebugInfo(): boolean;
        getInventory(): $Inventory;
        isAffectedByFluids(): boolean;
        getScoreboard(): $Scoreboard;
        handler$zei000$l2weaponry$blockUsingShield_customShield(arg0: $LivingEntity, arg1: $CallbackInfo): void;
        handler$zei000$l2weaponry$disableShield_customShield(arg0: $CallbackInfo): void;
        handler$gep000$taxfreelevels$rememberExperienceLevel(enchantedItem: $ItemStack_, experienceLevels: number, ci: $CallbackInfo, previousLevel: $LocalIntRef): void;
        handler$gfd000$taxfreelevels$flattenEnchantmentCost(enchantedItem: $ItemStack_, experienceLevels: number, ci: $CallbackInfo, previousLevel: $LocalIntRef): void;
        getDefaultDimensions(arg0: $Pose_): $EntityDimensions;
        isDisableBodyRotation(): boolean;
        setDisableBodyRotation(disableBodyRotation: boolean): void;
        getExposureCameraActionAnim(partialTick: number): number;
        irons_lib$getArmorBySlotRaw(arg0: $EquipmentSlot_): $ItemStack;
        updateTutorialInventoryAction(arg0: $ItemStack_, arg1: $ItemStack_, arg2: $ClickAction_): void;
        getPlayerAwardedForExposure(): $Optional<any>;
        getCurrentItemAttackStrengthDelay(): number;
        getInventoryChangeListener(): $KubeJSInventoryListener;
        handler$ggd000$artifacts$eat(level: $Level_, stack: $ItemStack_, properties: $FoodProperties_, cir: $CallbackInfoReturnable<any>): void;
        playerAnimator_getAnimation(): $AnimationApplier;
        playerAnimator_getAnimation(id: $ResourceLocation_): $IAnimation;
        playerAnimator_setAnimation(id: $ResourceLocation_, animation: $IAnimation): $IAnimation;
        tryResetCurrentImpulseContext(): void;
        isUpdated(frameId: number): number;
        setUpdated(frameId: number): void;
        setMainArm(arg0: $HumanoidArm_): void;
        isScoping(): boolean;
        isHurt(): boolean;
        canEat(arg0: boolean): boolean;
        setIgnoreFallDamageFromCurrentImpulse(arg0: boolean): void;
        handler$dgk005$notenoughanimations$tick(info: $CallbackInfo): void;
        isIgnoringFallDamageFromCurrentImpulse(): boolean;
        handler$ejo000$railways$addModDataVersions(arg0: $CompoundTag_, arg1: $CallbackInfo): void;
        localvar$fdn000$fruitsdelight$canEat(arg0: boolean): boolean;
        blockActionRestricted(arg0: $Level_, arg1: $BlockPos_, arg2: $GameType_): boolean;
        causeFoodExhaustion(arg0: number): void;
        tryToStartFallFlying(): boolean;
        giveExperiencePoints(arg0: number): void;
        getXpNeededForNextLevel(): number;
        onEnchantmentPerformed(arg0: $ItemStack_, arg1: number): void;
        triggerRecipeCrafted(arg0: $RecipeHolder_<never>, arg1: $List_<$ItemStack_>): void;
        openMinecartCommandBlock(arg0: $BaseCommandBlock): void;
        startAutoSpinAttack(arg0: number, arg1: number, arg2: $ItemStack_): void;
        resetCurrentImpulseContext(): void;
        isSleepingLongEnough(): boolean;
        setEntityOnShoulder(arg0: $CompoundTag_): boolean;
        getShoulderEntityRight(): $CompoundTag;
        hasCorrectToolForDrops(arg0: $BlockState_, arg1: $Level_, arg2: $BlockPos_): boolean;
        /**
         * @deprecated
         */
        hasCorrectToolForDrops(arg0: $BlockState_): boolean;
        canUseGameMasterBlocks(): boolean;
        getLastDeathLocation(): ($GlobalPos) | undefined;
        isSecondaryUseActive(): boolean;
        getAttackStrengthScale(arg0: number): number;
        blockInteractionRange(): number;
        canInteractWithBlock(arg0: $BlockPos_, arg1: number): boolean;
        getShoulderEntityLeft(): $CompoundTag;
        entityInteractionRange(): number;
        getPlayerExecutingExposure(): $Optional<any>;
        canInteractWithEntity(arg0: $Entity, arg1: number): boolean;
        canInteractWithEntity(arg0: $AABB_, arg1: number): boolean;
        getWardenSpawnTracker(): ($WardenSpawnTracker) | undefined;
        getEnderChestInventory(): $PlayerEnderChestContainer;
        setReducedDebugInfo(arg0: boolean): void;
        giveExperienceLevels(arg0: number): void;
        setLastDeathLocation(arg0: ($GlobalPos_) | undefined): void;
        supplementaries$setQuiver(arg0: $ItemStack_): void;
        supplementaries$getQuiver(): $ItemStack;
        getItemSwapAnimationTimer(): number;
        getLastAnimationSwapTick(): number;
        setLastAnimationSwapTick(count: number): void;
        getCraftingGrid(): $InventoryKJS;
        removeActiveExposureCamera(): void;
        setRotateBodyToHead(rotateBodyToHead: boolean): void;
        getExposureCameraOperator(): $Optional<any>;
        getExposureAuthorEntity(): $Entity;
        setItemSwapAnimationTimer(count: number): void;
        tlmInRemoveVehicleCooldown(): boolean;
        setActiveExposureCamera(camera: $Camera): void;
        isTextFilteringEnabled(): boolean;
        getActiveExposureCamera(): $Camera;
        modifyReturnValue$fdn000$fruitsdelight$getFoodData(arg0: $FoodData): $FoodData;
        openMenu(arg0: $MenuProvider, arg1: $Consumer_<$RegistryFriendlyByteBuf>): $OptionalInt;
        openMenu(arg0: $MenuProvider, arg1: $BlockPos_): $OptionalInt;
        isCloseEnough(arg0: $Entity, arg1: number): boolean;
        isFakePlayer(): boolean;
        mayFly(): boolean;
        /**
         * @deprecated
         */
        getAnimation(): $AnimationApplier;
        asHolderEntity(): $Entity;
        getServerPlayerExecutingExposure(): ($ServerPlayer) | undefined;
        getServerPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        asOperatorEntity(): $LivingEntity;
        getActiveExposureCameraOptional(): ($Camera) | undefined;
        supplementaries$hasQuiver(): boolean;
        clearMeshes(): void;
        getStats(): $PlayerStatsJS;
        isMiningBlock(): boolean;
        giveInHand(item: $ItemStack_): void;
        getMouseItem(): $ItemStack;
        setMouseItem(item: $ItemStack_): void;
        addFood(hunger: number, saturation: number): void;
        getFoodLevel(): number;
        setFoodLevel(foodLevel: number): void;
        getSaturation(): number;
        addExhaustion(exhaustion: number): void;
        setSaturation(saturation: number): void;
        addXPLevels(levels: number): void;
        setXpLevel(levels: number): void;
        getXpLevel(): number;
        notify(builder: $NotificationToastData_): void;
        notify(title: $Component_, text: $Component_): void;
        give(item: $ItemStack_): void;
        /**
         * Checks if the player is fake.
         */
        isFake(): this is $FakePlayer;
        addXP(xp: number): void;
        setXp(xp: number): void;
        getXp(): number;
        sendInventoryUpdate(): void;
        getSelectedSlot(): number;
        setSelectedSlot(index: number): void;
        getOpenInventory(): $AbstractContainerMenu;
        boostElytraFlight(): void;
        addItemCooldown(item: $Item_, ticks: number): void;
        sendData(channel: string, data: $CompoundTag_): void;
        sendData(channel: string): void;
        invokeSetShoulderEntityRight(arg0: $CompoundTag_): void;
        invokeSetShoulderEntityLeft(arg0: $CompoundTag_): void;
        malilib_getEnderItems(): $PlayerEnderChestContainer;
        serializeNBT(arg0: $HolderLookup$Provider): $Player;
        static DEFAULT_BASE_GRAVITY: number;
        hasImpulse: boolean;
        static USE_ITEM_INTERVAL: number;
        yHeadRot: number;
        yCloakO: number;
        noPhysics: boolean;
        yo: number;
        yBodyRotO: number;
        removalReason: $Entity$RemovalReason;
        zza: number;
        swingingArm: $InteractionHand;
        static CRAFTING_SLOT_OFFSET: number;
        static ID_TAG: string;
        static DATA_HEALTH_ID: $EntityDataAccessor<number>;
        static WAKE_UP_DURATION: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        zo: number;
        walkDist: number;
        noCulling: boolean;
        walkAnimation: $WalkAnimationState;
        static STANDING_DIMENSIONS: $EntityDimensions;
        yya: number;
        oAttackAnim: number;
        yHeadRotO: number;
        static UUID_TAG: string;
        static DEFAULT_MODEL_CUSTOMIZATION: number;
        hurtDuration: number;
        static DEATH_DURATION: number;
        portalProcess: $PortalProcessor;
        static SWIMMING_BB_HEIGHT: number;
        static DEFAULT_ENTITY_INTERACTION_RANGE: number;
        dead: boolean;
        verticalCollision: boolean;
        verticalCollisionBelow: boolean;
        experienceLevel: number;
        static DEFAULT_BABY_SCALE: number;
        eyeHeight: number;
        static ATTRIBUTES_FIELD: string;
        static PERSISTED_NBT_TAG: string;
        static DEFAULT_BB_HEIGHT: number;
        xxa: number;
        zCloak: number;
        flyDist: number;
        currentImpulseImpactPos: $Vec3;
        static PASSENGERS_TAG: string;
        xCloakO: number;
        wasOnFire: boolean;
        attackAnim: number;
        zOld: number;
        timeOffs: number;
        wasTouchingWater: boolean;
        activeEffects: $Map<$Holder<$MobEffect>, $MobEffectInstance>;
        rotA: number;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        static ENDER_SLOT_OFFSET: number;
        static ARMOR_SLOT_OFFSET: number;
        static SLEEP_DURATION: number;
        static HELD_ITEM_SLOT: number;
        yCloak: number;
        swingTime: number;
        static BODY_ARMOR_OFFSET: number;
        xCloak: number;
        tickCount: number;
        static BOARDING_COOLDOWN: number;
        static MAX_HEALTH: number;
        static SWING_DURATION: number;
        yRotO: number;
        static MIN_MOVEMENT_DISTANCE: number;
        static CONTENTS_SLOT_INDEX: number;
        static BASE_JUMP_POWER: number;
        static DEFAULT_EYE_HEIGHT: number;
        level: $Level;
        static CROUCH_BB_HEIGHT: number;
        moveDist: number;
        zCloakO: number;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        bob: number;
        experienceProgress: number;
        totalExperience: number;
        xOld: number;
        wasInPowderSnow: boolean;
        containerMenu: $AbstractContainerMenu;
        hurtTime: number;
        swinging: boolean;
        hurtMarked: boolean;
        attackStrengthTicker: number;
        static DEFAULT_MAIN_HAND: $HumanoidArm;
        deathTime: number;
        static EQUIPMENT_SLOT_OFFSET: number;
        invulnerableTime: number;
        jumping: boolean;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        static DEFAULT_VEHICLE_ATTACHMENT: $Vec3;
        inventoryMenu: $InventoryMenu;
        inventory: $Inventory;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static ARMOR_SLOTS: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        random: $RandomSource;
        static PLAYER_HURT_EXPERIENCE_TIME: number;
        yOld: number;
        static HAND_SLOTS: number;
        static DEFAULT_BB_WIDTH: number;
        minorHorizontalCollision: boolean;
        static EXTRA_RENDER_CULLING_SIZE_WITH_BIG_HAT: number;
        fishing: $FishingHook;
        removeArrowTime: number;
        walkDistO: number;
        static SWIMMING_BB_WIDTH: number;
        static FREEZE_HURT_FREQUENCY: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        yBodyRot: number;
        blocksBuilding: boolean;
        takeXpDelay: number;
        static DEFAULT_BLOCK_INTERACTION_RANGE: number;
        oBob: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        invulnerableDuration: number;
        BAGU_ANIMATION_CONTROLLER: $BaguAnimationController<any>;
        removeStingerTime: number;
        static BASE_SAFE_FALL_DISTANCE: number;
        effectsDirty: boolean;
        currentExplosionCause: $Entity;
        constructor(arg0: $Level_, arg1: $BlockPos_, arg2: number, arg3: $GameProfile);
        get prefixes(): $Collection<$MutableComponent>;
        get creative(): boolean;
        get suffixes(): $Collection<$MutableComponent>;
        get animationStack(): $AnimationStack;
        get lastHeldItems(): $ItemStack[];
        set thinArms(value: boolean);
        get enchantmentSeed(): number;
        get foodData(): $FoodData;
        get cooldowns(): $ItemCooldowns;
        get sleepTimer(): number;
        static get dataPlayerModeCustomisation$irons_lib_$md$70d283$0(): $EntityDataAccessor<any>;
        get luck(): number;
        get stages(): $Stages;
        get abilities(): $Abilities;
        get localPlayer(): boolean;
        get gameProfile(): $GameProfile;
        get affectedByFluids(): boolean;
        get scoreboard(): $Scoreboard;
        get playerAwardedForExposure(): $Optional<any>;
        get currentItemAttackStrengthDelay(): number;
        get inventoryChangeListener(): $KubeJSInventoryListener;
        set mainArm(value: $HumanoidArm_);
        get scoping(): boolean;
        get hurt(): boolean;
        set ignoreFallDamageFromCurrentImpulse(value: boolean);
        get ignoringFallDamageFromCurrentImpulse(): boolean;
        get xpNeededForNextLevel(): number;
        get sleepingLongEnough(): boolean;
        set entityOnShoulder(value: $CompoundTag_);
        get shoulderEntityRight(): $CompoundTag;
        get secondaryUseActive(): boolean;
        get shoulderEntityLeft(): $CompoundTag;
        get playerExecutingExposure(): $Optional<any>;
        get wardenSpawnTracker(): ($WardenSpawnTracker) | undefined;
        get enderChestInventory(): $PlayerEnderChestContainer;
        get craftingGrid(): $InventoryKJS;
        get exposureCameraOperator(): $Optional<any>;
        get exposureAuthorEntity(): $Entity;
        get textFilteringEnabled(): boolean;
        get fakePlayer(): boolean;
        get animation(): $AnimationApplier;
        get serverPlayerExecutingExposure(): ($ServerPlayer) | undefined;
        get serverPlayerAwardedForExposure(): ($ServerPlayer) | undefined;
        get activeExposureCameraOptional(): ($Camera) | undefined;
        get stats(): $PlayerStatsJS;
        get miningBlock(): boolean;
        get fake(): boolean;
        get openInventory(): $AbstractContainerMenu;
    }
}
